### ISSUE TITLE
datamodel + report deplyoment together with refresh fails

### ISSUE THREAD

**Issue by TarekSalha** [pbi-tools/pbi-tools#165]
I am using the following version:

  "version": "1.0.0-rc.2+20220703",
  "edition": "Desktop",
  "build": "1.0.22184.2331",
  "pbixProjVersion": "0.12",
  "pbiBuildVersion": "2.106.582.0",
  "amoVersion": "19.42.0.4"

I am deploying to power bi service using a pbiproj manifest as well as a folder containing the source like this:

`(base) PS C:\Users\TarekSalha> pbi-tools deploy .\source\bi\PowerBI myReportWithDatamodel`

this works fine, but after the refresh completed the refresh summary is not being displayed. I am not using the new detailed refresh report and I suspect, that somewhere in the code you are expecting this item to be in place. This is the manifest I use:

```
{
    "version": "0.1.0",
    "created": "2022-05-25T15:24:03.2613259+01:00",
    "lastModified": "2022-07-05T16:57:10.0801642+02:00",
    "deployments": {
      "myReportWithDatamodel": {
        "mode": "Dataset",
        "source": {
          "type": "Folder",
          "path": "./myReportWithDatamodel"
        },
        "authentication": {
          "type": "ServicePrincipal",
          "tenantId": "myTenantId",
          "clientId": "myClientId",
          "clientSecret": "myClientSecret"
        },
        "options": {
          "refresh": {
            "skipNewDataset": true,
            "method": "XMLA",
            "type": "Full"
          },
          "dataset": {
            "replaceParameters": true,
            "deployEmbeddedReport": true
          }
        },
        "parameters": {
          "Version": "0.1.0",
          "GH-Branch": "%GITHUB_REF_NAME%",
          "GH-RunId": "%GITHUB_RUN_ID%",
          "GH-SHA": "%GITHUB_SHA%",
          "env": "PROD"
        },
        "environments": {
          "Development": {
            "workspace": "Data Lake DEV",
            "refresh": true
          },
          "STAGE": {
            "workspace": "Data Lake STAGE",
            "displayName": "{{PBIXPROJ_FOLDER}} STAGE",
            "refresh": true
          },
          "PROD": {
            "workspace": "Data Lake",
            "refresh": true
          }
        }
      }
    }
  }
```

Below you will find the (pii filtered :-) ) output of the command:

```
Reading PBIXPROJ settings from: C:\...\.pbixproj.json
Starting deployment 'Area_Selection' into environment: Development ...
Reading PBIXPROJ settings from: C:\...\myReportWithDatamodel\.pbixproj.json
Using Power BI Desktop install: 2.106.883.0 (22.06) at C:\Program Files\Microsoft Power BI Desktop\bin
Access token received. Expires On: 07/14/2022 19:41:06 +00:00
Resolved workspace ID 'myWorkspaceId' for workspace: 'Data Lake DEV'
Connecting to XMLA endpoint: powerbi://api.powerbi.com/v1.0/myorg/Data Lake DEV
Found existing dataset.
TOM Database Properties:
* ID                    : MyDatasetId
* Name                  : myReportWithDatamodel
* Description           :
* CompatibilityLevel    : 1550
* CreatedTimestamp      : 07/13/2022 12:37:32
* StructureModifiedTime : 07/13/2022 13:23:51
* EstimatedSize         : 
Update Results:

Model deployment succeeded.
Power BI Dataset Details:
* ID                     : myDatasetId
* Name                   : myReportWithDatamodel
* WebUrl                 : https://app.powerbi.com/...
* ConfiguredBy           : 
* CreatedDate            : 07/13/2022 10:37:32
* IsRefreshable          : True
* IsOnPremGatewayRequired: False
* TargetStorageMode      : Abf
Generating report connections file from embedded default template.
Creating PBIX from report source at: 'C:\...\myReportWithDatamodel.pbix'...
Reading PBIXPROJ settings from: C:\...\myReportWithDatamodel\.pbixproj.json
Generating PBIX file at 'C:\...\myReportWithDatamodel.pbix'...
Import: myReportWithDatamodel.pbix, State: Publishing (Id: someId)
Import succeeded: someId (myReportWithDatamodel.pbix)
        Report: someId "myReportWithDatamodel"
        Url: https://app.powerbi.com/groups/...
Report Created: 07/13/2022 10:37:44
Report Updated: 07/14/2022 18:41:19
Starting dataset refresh (Full) ...
Refresh Results:

An unhandled exception occurred.
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PbiTools.Deployments.DeploymentManager.RefreshXmla(Database database, RefreshOptions refreshOptions, String basePath) in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:Zeile 339.
   bei PbiTools.Deployments.DeploymentManager.<DeployDatasetAsync>d__32.MoveNext() in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:Zeile 306.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Deployments\DeploymentManager.cs:Zeile 84.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Cli\Deploy.cs:Zeile 39.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei PowerArgs.ArgAction.Invoke()
   bei PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Program.cs:Zeile 94.
---> (Interne Ausnahme #0) System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei PbiTools.Deployments.DeploymentManager.RefreshXmla(Database database, RefreshOptions refreshOptions, String basePath) in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:Zeile 339.
   bei PbiTools.Deployments.DeploymentManager.<DeployDatasetAsync>d__32.MoveNext() in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:Zeile 306.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Deployments\DeploymentManager.cs:Zeile 84.<---
```

**Comment by mthierba** [comment]
I believe this is an unfortunate error being triggered when logging refresh warnings returned from the XMLA server. Fixed what I think is causing the issue - it'll be available in the next RC.2 preview, coming later this week. Thanks for reporting!

**Comment by mthierba** [comment]
Could you please test again with the latest (rc.2+preview.4) release?

**Comment by TarekSalha** [comment]
Unfortunately, I can do earliest in 2 weeks as I am OOO. I‘ll report back then.

**Comment by ingthu** [comment]
Hi!
I also had above error described before but now I have changed to version "1.0.0-rc.2+preview.4" and the problem is gone. But instead I have another error. If I remove "refresh": true in the manifest then it works but the refresh will not start.

    "environments": {
        "TEST": {
          "workspace": "XXXXX",
          "refresh": true,
          "report": {
            "skip": false
          }
        }
      }

The error message I get.

An unhandled exception occurred.
Newtonsoft.Json.JsonSerializationException: Error converting value True to type 'PbiTools.Deployments.PbiDeploymentEnvironment+RefreshOptions'. Path 'environments.TEST.refresh'. ---> System.ArgumentException: Could not cast or convert from System.Boolean to PbiTools.Deployments.PbiDeploymentEnvironment+RefreshOptions.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)  
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at PbiTools.Deployments.PbiDeploymentManifest.<>c.<FromProject>b__32_0(KeyValuePair`2 x) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Deployments\DeploymentManifest.cs:line 51
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at PbiTools.Deployments.PbiDeploymentManifest.FromProject(PbixProject project) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Deployments\DeploymentManifest.cs:line 50
   at PbiTools.Deployments.DeploymentManager..ctor(PbixProject project, AppSettings appSettings) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Deployments\DeploymentManager.cs:line 38
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Cli\Deploy.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Program.cs:line 94

**Comment by mthierba** [comment]
Hi, the preview.4 has a breaking change in the manifest with respect to dataset refresh. I will document and announce this properly, but haven't been able yet since I'm on summer holiday.

Refresh now needs to be enabled at the manifest-level (**options.refresh.enabled** : bool). Each environment, in turn, can _opt out_ of the refresh (previously, it was an opt-in model): **env.refresh.skip** : bool (default: false).

Those kinds of breaking changes are generally avoided, but can happen whilst those features are in preview state.

See this example project: https://github.com/pbi-tools/contoso-sql-dataset-devops/blob/main/.pbixproj.json

**Comment by ingthu** [comment]
Thanks it works perfectly!

**Comment by TarekSalha** [comment]
works for me now as well
