### ISSUE TITLE
The specified path, file name, or both are too long.

### ISSUE THREAD

**Issue by vasim07** [pbi-tools/pbi-tools#185]
I have a long (really long) title in the report.

When I use `pbi-tools extract DatGoodWill\ATR.pbix`. It raises the following errror.

`An unhandled exception occurred.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at PbiTools.FileSystem.ProjectFolder.WriteFile[T](String path, Func`2 factory, Action'1 callback) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 141
   at PbiTools.FileSystem.ProjectFolder.WriteText(String path, Action`'1 onTextWriterAvailable) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 137
   at PbiTools.Utils.JsonExtensions.ExtractAndParseTokenAs[T](JObject parent, String property, IProjectFolder folder) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Utils\JsonExtensions.cs:line 71
   at PbiTools.Serialization.ReportSerializer.Serialize(JObject content) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Serialization\ReportSerializer.cs:line 97
   at PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Model\PbixModel.cs:line 276
   at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Nullable`1 pid, Nullable`1 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization, Boolean watch) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Cli\Extract.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Program.cs:line 94`

I can see Root folder > Report > sections > 001_pageName > visualContainer

Under visualContainer - directory of the first visual (small title) is visible.
However, there is no directory of the second visual, this the visual which has a long (really long) title.

Yes, the title needs to be that long!

**Comment by Seebaer1986** [comment]
Hi @vasim07, your issue is known. Please see #56 for further details.
