### ISSUE TITLE
An unhandled exception occurred. System.IO.DirectoryNotFoundException: Could not find a part of the path (1.0.0-rc.2)

### ISSUE THREAD

**Issue by AngusHelloData** [pbi-tools/pbi-tools#188]
Thanks for providing this - really looking forward to getting this working! Ran it twice, got the same error message. It crashes on one of the earliest bookmarks. 

Path does exist - copied from Windows folder below - and matches to the error output: 
C:\Users\customer\Dropbox\PowerBI\Client Projects\Hello Data Working\pbi-tools\PBIX\v1.33\Hello Data v1.33 - Staff - HelloDataLive\Report\bookmarks\Reception On Track\ROT Percentages\sections\ReportSection3ea556b03f02732c79f4\visualContainers

Error output:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\customer\Dropbox\PowerBI\Client Projects\Hello Data Working\pbi-tools\PBIX\v1.33\Hello Data v1.33 - Staff - HelloDataLive\Report\bookmarks\Reception On Track\ROT Percentages\sections\ReportSection3ea556b03f02732c79f4\visualContainers\VisualContainer2.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.CreateText(String path)
   at PbiTools.FileSystem.ProjectFolder.WriteFile[T](String path, Func`2 factory, Action`1 callback) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 151
   at PbiTools.FileSystem.ProjectFolder.WriteText(String path, Action`1 onTextWriterAvailable) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 137
   at PbiTools.Serialization.ReportSerializer.SerializeBookmarks(IEnumerable`1 jBookmarks, IProjectFolder baseFolder) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Serialization\ReportSerializer.cs:line 161
   at PbiTools.Serialization.ReportSerializer.SerializeBookmarks(IEnumerable`1 jBookmarks, IProjectFolder baseFolder) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Serialization\ReportSerializer.cs:line 127
   at PbiTools.Serialization.ReportSerializer.Serialize(JObject content) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Serialization\ReportSerializer.cs:line 77
   at PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Model\PbixModel.cs:line 276
   at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Nullable`1 pid, Nullable`1 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization, Boolean watch) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Cli\Extract.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Program.cs:line 94

**Comment by AngusHelloData** [comment]
ran it with rc 1 version and got the more specific error message of path name too long (> 200 chars)
renamed the pbix to HD.pbix to reduce pathfilename length and ran successfully!

suggest a better error message? Thanks!! Looking forward to using it on big pbix!
