### ISSUE TITLE
HTTP Errors, Unhandled exceptions.

### ISSUE THREAD

**Issue by guillermojleonr** [pbi-tools/pbi-tools#200]
Hello everyone, hope you are all doing well. 

I'm trying to complete a deployment process, and I've had some issues along the way. 

This is the case:

- From PowerBI Service added some content to my workspace, by doing this I'm gaining access to a Report and a Dataset.
- Downloaded the report to my local machine, made a modification, decompiled the file, pushed it to github, and configurated the environment and secret.

When the workflow runs I've had some HTTP Errors. 

```
System.AggregateException: One or more errors occurred. (HTTP Error: BadRequest
{
  "error": {
    "code": "FileFormatUserException",
    "pbi.error": {
      "code": "FileFormatUserException",
      "parameters": {},
      "details": [],
      "exceptionCulprit": 1
    }
  }
```

is one of them, also had 

```
System.AggregateException: One or more errors occurred. (HTTP Error: PreconditionFailed
{
  "error": {
    "code": "DuplicatePackageWithOtherContentProviderError",
    "pbi.error": {
      "code": "DuplicatePackageWithOtherContentProviderError",
```

It's been really hard for me to find documentation about these exceptions, I've looked in Google and PowerBI API documentation but I can't find anything.

I'm not sure if this has something to do with pbi-tools because I guess these are code errors coming from the PowerBI API REST system.

The only thing that I can do is to try to understand the logic behind this process and modify the file, the deployment manifests, or whatever is messing with this.

My question is very simple: How should I proceed? Should I post an Issue here for each code exception that I can't understand?

Thanks.

**Comment by mthierba** [comment]
You're correct, those are error messages from the PBI API. I could help if I had access to your manifest (as that would reveal which API calls are made). Also a full `pbi-tools deploy` output log would help.

**Comment by guillermojleonr** [comment]
This is the repository that I'm using where you can see my deployment manifest, it has got two Reports inside, one of them has a Model folder, and the other one doesn't.

https://github.com/guillermojleonr/devops-github-reports-pbixproj

This is the current output I'm getting

```
Run /app/pbi-tools/pbi-tools.core deploy . "$PROFILE"
Reading PBIXPROJ settings from: /__w/devops-github-reports-pbixproj/devops-github-reports-pbixproj/.pbixproj.json
Starting deployment 'All Reports' into environment: Development ...
Found [1](https://github.com/guillermojleonr/devops-github-reports-pbixproj/actions/runs/3421790851/jobs/5698395035#step:6:1) source folders to deploy.
Creating PBIX from report source at: '%TEMP%/348[7](https://github.com/guillermojleonr/devops-github-reports-pbixproj/actions/runs/3421790851/jobs/5698395035#step:6:8)2219-95b4-4b44-90c2-3f2cdf9d0aa2/test_file.pbix'...
Reading PBIXPROJ settings from: /__w/devops-github-reports-pbixproj/devops-github-reports-pbixproj/development_workspace/test_file/.pbixproj.json
Generating PBIX file at '%TEMP%/34[8](https://github.com/guillermojleonr/devops-github-reports-pbixproj/actions/runs/3421790851/jobs/5698395035#step:6:9)7221[9](https://github.com/guillermojleonr/devops-github-reports-pbixproj/actions/runs/3421790851/jobs/5698395035#step:6:10)-95b4-4b44-90c2-3f2cdf9d0aa2/test_file.pbix'...
Package part written: /Version
Package part written: /Settings
Package part written: /Metadata
Package part written: /DiagramLayout
Package part written: /Report/Layout
Package part written: /Report/StaticResources/SharedResources/BaseThemes/CY21SU[11](https://github.com/guillermojleonr/devops-github-reports-pbixproj/actions/runs/3421790851/jobs/5698395035#step:6:12).json
Access token received. Expires On: 11/08/2022 [18](https://github.com/guillermojleonr/devops-github-reports-pbixproj/actions/runs/3421790851/jobs/5698395035#step:6:19):34:44 +00:00
Resolved workspace ID 'bb07f3d3-e1fe-4eda-9d54-9d0[19](https://github.com/guillermojleonr/devops-github-reports-pbixproj/actions/runs/3421790851/jobs/5698395035#step:6:20)8c00f85' for workspace: 'development_workspace'
Import: null, State: Failed (Id: a2c0c5cb-6aef-460a-8dbf-b3291c61faa9)
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. (Deployment '' (a2c0c5cb-6aef-460a-8dbf-b3291c61faa9) failed.)
 ---> PbiTools.Deployments.DeploymentException: Deployment '' (a2c0c5cb-6aef-460a-8dbf-b3291c61faa9) failed.
   at PbiTools.Deployments.DeploymentManager.ImportReportAsync(ReportDeploymentInfo args, IPowerBIClient powerbi, String workspace, IDictionary`2 workspaceIdCache) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:line 458
   at PbiTools.Deployments.DeploymentManager.DeployReportAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:line 184
   at PbiTools.Deployments.DeploymentManager.DeployAsync(String profileName, String environment) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:line 99
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Cli\Deploy.cs:line 41
--- End of stack trace from previous location ---
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Program.cs:line 88
Error: Process completed with exit code [24](https://github.com/guillermojleonr/devops-github-reports-pbixproj/actions/runs/3421790851/jobs/5698395035#step:6:25)7.
```

As you can see I'm not getting `FileFormatUserException` nor `DuplicatePackageWithOtherContentProviderError` this time I got 
`System.AggregateException: One or more errors occurred. (Deployment '' (a2c0c5cb-6aef-460a-8dbf-b3291c61faa9) failed.)`
