### ISSUE TITLE
RequestedFileIsEncryptedOrCorrupted on deploy using GitHub actions

### ISSUE THREAD

**Issue by LukasSchauffele** [pbi-tools/pbi-tools#201]
Hi @mthierba - I hope you can help with the below. When I run locally everything works fine, reports are deployed to correct workspace. When I run via GitHub actions I get an error. I've tried a few different versions of pbi-tools, but all are resulting in the same error.

Appreciate your help.

```json
{
  "version": "0.11",
  "created": "2022-11-08T14:18:21.4437286+11:00",
  "deployments": {
    "Files": {
      "description": "This profile deploys a number of reports from .pbix files. One of the path segments, {{WORKSPACE}}, is used as a deployment parameter for a destination workspace name.",
      "mode": "Report",
      "source": {
        "type": "File",
        "path": "./Reports/*.pbix"
      },
      "authentication": {
        "type": "ServicePrincipal",
        "authority": "https://login.microsoftonline.com/**",
        "validateAuthority": true,
        "tenantId": "03c0da**",
        "clientId": "510e8b**",
        "clientSecret": "%PBI_CLIENT_SECRET%"
      },
      "options": {
        "import": {
          "nameConflict": "CreateOrOverwrite"
        }
      },
      "environments": {
        "Development": {
          "workspace": "test-automated-deployment"
        }
      }
    }
  }
}
```

```yml
name: Deploy-Staging

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      whatIf:
        description: 'Enable WhatIf Mode'
        type: boolean
        required: true
        default: true

env:
  PROFILE: Files
  ENVIRONMENT: Development

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: Development
    container:
      image: ghcr.io/pbi-tools/pbi-tools-core:1.0.0-rc.2_20220525

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: pbi-tools info
        run: |
          /app/pbi-tools/pbi-tools.core info
      - name: pbi-tools deploy (WhatIf)
        if: ${{ github.event.inputs.whatIf == 'true' }}
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" "$ENVIRONMENT" -whatIf
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}

      - name: pbi-tools deploy
        if: ${{ github.event.inputs.whatIf != 'true' }}
        run: |
          /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" "$ENVIRONMENT"
        env:
          PBI_CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}

```

Error output on pbi-tools deploy step:
```log
Run /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" "$ENVIRONMENT"
  /app/pbi-tools/pbi-tools.core deploy . "$PROFILE" "$ENVIRONMENT"
  shell: sh -e {0}
  env:
    PROFILE: Files
    ENVIRONMENT: Development
    PBI_CLIENT_SECRET: ***
Reading PBIXPROJ settings from: /__w/quality-assurance-pbi/quality-assurance-pbi/.pbixproj.json
Starting deployment 'Files' into environment: Development ...
Found [2](https://github.com/Fleetwood-Australia/quality-assurance-pbi/actions/runs/3416430752/jobs/5686567519#step:6:2) source files to deploy.
Both TenantId and Authority are provided. 'TenantId' will be ignored.
Access token received. Expires On: 11/08/2022 05:40:44 +00:00
Resolved workspace ID '22e0549e-4ed6-444d-9ce1-5[3](https://github.com/Fleetwood-Australia/quality-assurance-pbi/actions/runs/3416430752/jobs/5686567519#step:6:3)19e19a2001' for workspace: 'test-automated-deployment'
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. (HTTP Error: BadRequest
{
  "error": {
    "code": "RequestedFileIsEncryptedOrCorrupted",
    "pbi.error": {
      "code": "RequestedFileIsEncryptedOrCorrupted",
      "parameters": {},
      "details": [],
      "exceptionCulprit": 1
    }
  }
})
 ---> PbiTools.Deployments.DeploymentException: HTTP Error: BadRequest
{
  "error": {
    "code": "RequestedFileIsEncryptedOrCorrupted",
    "pbi.error": {
      "code": "RequestedFileIsEncryptedOrCorrupted",
      "parameters": {},
      "details": [],
      "exceptionCulprit": 1
    }
  }
}
 ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.PowerBI.Api.ImportsOperations.UploadFile(Nullable`1 groupId, Stream file, String datasetDisplayName, Nullable`1 nameConflict, Nullable`1 skipReport, Nullable`1 overrideReportLabel, Nullable`1 overrideModelLabel, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.PowerBI.Api.ImportsOperations.PostImportFileWithHttpMessage(Nullable`1 groupId, Stream file, String datasetDisplayName, Nullable`1 nameConflict, Nullable`1 skipReport, Nullable`1 overrideReportLabel, Nullable`1 overrideModelLabel, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.PowerBI.Api.ImportsOperationsExtensions.PostImportWithFileAsyncInGroup(IImportsOperations operations, Guid groupId, Stream fileStream, String datasetDisplayName, Nullable`1 nameConflict, Nullable`1 skipReport, Nullable`1 overrideReportLabel, Nullable`1 overrideModelLabel, CancellationToken cancellationToken)
   at PbiTools.Deployments.DeploymentManager.ImportReportAsync(ReportDeploymentInfo args, IPowerBIClient powerbi, String workspace, IDictionary`2 workspaceIdCache) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 331
   at PbiTools.Deployments.DeploymentManager.DeployReportAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 99
   --- End of inner exception stack trace ---
   at PbiTools.Deployments.DeploymentManager.DeployReportAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 103
   at PbiTools.Deployments.DeploymentManager.DeployAsync(String profileName, String environment) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Deployments\DeploymentManager.cs:line 93
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Cli\Deploy.cs:line [4](https://github.com/Fleetwood-Australia/quality-assurance-pbi/actions/runs/3416430752/jobs/5686567519#step:6:4)1
--- End of stack trace from previous location ---
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Program.cs:line 88
Error: Process completed with exit code 24[7](https://github.com/Fleetwood-Australia/quality-assurance-pbi/actions/runs/3416430752/jobs/5686567519#step:6:7).
```

**Comment by LukasSchauffele** [comment]
When running with `-WhatIf` flag it completes without issues...

<img width="734" alt="CleanShot 2022-11-08 at 16 03 07@2x" src="https://user-images.githubusercontent.com/7881214/200479607-e57b26bd-c31f-461c-a971-ecb1349de8dc.png">

**Comment by mthierba** [comment]
Could you please post the `pbi-tools deploy` output from the -whatif run? That'll help. Also, I'd recommend to work with the latest version: https://github.com/pbi-tools/pbi-tools/pkgs/container/pbi-tools-core/45952683?tag=1.0.0-rc.2_preview.5

**Comment by mthierba** [comment]
So, to recap:
- `pbi-tools deploy` works in PBIX upload mode fine when run on a local Windows machine
- it fails with the same file when run on a Ubuntu GitHub runner?
- all settings are the same otherwise

The error message seems to suggest that the PBIX files have sensitivity labels applied, i.e. are encrypted. Is that the case?

**Comment by LukasSchauffele** [comment]
Yes, that's correct.

Do you think I misconfigured something on the git side? Something to do with lfs maybe?

The files are not encrypted.

BTW, I noticed in the what if run, it incorrectly uses the same `* FILE_NAME = "ITPs Dashboard JDM.pbix"` for both files. I renamed one of the files but it didn't have anything to do with this issue.

![CleanShot 2022-11-08 at 19 51 56](https://user-images.githubusercontent.com/7881214/200519160-9648d728-55ea-4ea2-98de-6e03df332841.png)

**Comment by LukasSchauffele** [comment]
There you go that was it. I added the following to the checkout step and it worked without issues!

```yml
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
            lfs: true
```

Sorry, I should have figured that one out myself.

Danke für deine Hilfe!

**Comment by mthierba** [comment]
Awesome! Sorry, I should have asked about LFS. Agreed, this one likely hits you with confusing errors. Glad you got there!
