### ISSUE TITLE
Getting Unhandled exception error while extracting a PBI file

### ISSUE THREAD

**Issue by AdityaKSoni** [pbi-tools/pbi-tools#203]
While extracting a PBI file getting below error, 

Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.111.265.0_x64__8wekyb3d8bbwe\bin
An unhandled error occurred.
System.IO.FileFormatException: File contains corrupted data.
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at Microsoft.PowerBI.Packaging.PowerBIPackager.Open(Stream storageStream, Boolean& requiresConversionToReportLayout, Byte[]& securityBindings, Version& pbixFileVersion, Boolean skipValidation)
   at PbiTools.PowerBI.PbixReader..ctor(String pbixPath, IDependenciesResolver resolver) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\PowerBI\PbixReader.cs:line 42
   at PbiTools.Cli.CmdLineActions.<>c__DisplayClass18_0.<ExtractWatchSession>g__ExtractAction|0() in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Cli\Extract.cs:line 136

Checked the code snippet for the class src/PBI-Tools/PowerBI/PbixReader.cs it is showing below snippet 

![image](https://user-images.githubusercontent.com/13534028/201024478-b792eb1d-8e7d-40b6-92ef-8fde1e2af378.png)

**Comment by mthierba** [comment]
If you manually change the file extension to .zip and try to open it as a Zip file in Explorer, does it succeed? If not, I won't be able to handle this, and your file is most likely encrypted, almost certainly due to a sensitivity label. Otherwise, I'm happy to debug, provided you can share the file.

**Comment by AdityaKSoni** [comment]
Thanks @mthierba , It is happening due to the encryption I think, when i extract the pbix file due to organisational settings its sensitivity by default comes as "Confidential", Our report is a thin report using a On prem analysis services, If i send it to you then you can not be able to see any data for visuals. Thanks again for the help
