### ISSUE TITLE
Unhandled Exception Occured When Extracting Custom Visuals

### ISSUE THREAD

**Issue by Jaws1990** [pbi-tools/pbi-tools#205]
Hi,

A colleague of mine is unable to extract a .pbix file to our source control as an unhandled exception is occurring when reaching the custom visuals extraction.

He has sent me the .pbix file itself and when I extract, the error does not occur.

We are extracting to exactly the same pbixproj folder with exactly the same content (we use the same branch). 

The path and folder in question does exist and we haven't made any custom visual updates. This is occurring with other reports too. Any ideas? Thanks in advance. 

`An unhandled exception occurred.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\******\source\repos\***\****\power-bi\power-bi-reports\audiencegrowth\CustomVisuals\clusteredBarChartD19A7DC39E0544CA85DAC6BF99637AD3\resources\clusteredBarChartD19A7DC39E0544CA85DAC6BF99637AD3.pbiviz.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at PbiTools.FileSystem.ProjectFolder.WriteFile[T](String path, Func``2 factory, Action``1 callback) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 149      
   at PbiTools.FileSystem.ProjectFolder.WriteFile(String path, Action``1 onStreamAvailable) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 130
   at PbiTools.Serialization.ResourcesSerializer.Serialize(IDictionary``2 content) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Serialization\ResourcesSerializer.cs:line 33
   at PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Model\PbixModel.cs:line 299
   at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Nullable``1 pid, Nullable``1 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization, Boolean watch) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Cli\Extract.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Program.cs:line 94`

**Comment by Jaws1990** [comment]
The user cloned the repo to a different location on their machine and this error no longer appears.
