### ISSUE TITLE
Unhandled Exception during model deployment

### ISSUE THREAD

**Issue by quinse** [pbi-tools/pbi-tools#206]
Firstly, thank you for this amazing tool!

I have been successfully running model deployments via Jenkins/Docker (on AWS ECS) and then suddenly today the deployments started failing with the error below.

I have tested with a more recent version of pbi-tools.core (I have been using 1.0.0-rc.2+20220703 but tested with , locally with a different docker container, with a different dataset and on a different workspace, all receive the same error.

`---
Connecting to XMLA endpoint: powerbi://api.powerbi.com/v1.0/myorg/WM-PBIP1-CorporateAnalytics-NonProd
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. (The server sent an unrecognizable response.)
 ---> Microsoft.AnalysisServices.ResponseFormatException: The server sent an unrecognizable response.
 ---> System.Xml.XmlException: '', hexadecimal value 0x06, is an invalid character.
   at System.Xml.XmlSqlBinaryReader.CheckText(Boolean attr)
   at System.Xml.XmlSqlBinaryReader.ScanOverValue(BinXmlToken token, Boolean attr, Boolean checkChars)
   at System.Xml.XmlSqlBinaryReader.ScanOverAnyValue(BinXmlToken token, Boolean attr, Boolean checkChars)
   at System.Xml.XmlSqlBinaryReader.ScanOverValue(BinXmlToken token, Boolean attr, Boolean checkChars)
   at System.Xml.XmlSqlBinaryReader.ScanAttributes()
   at System.Xml.XmlSqlBinaryReader.ImplReadElement()
   at System.Xml.XmlSqlBinaryReader.ReadDoc()
   at System.Xml.XmlSqlBinaryReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Xml.XmlReader.ReadStartElement(String localname, String ns)
   at Microsoft.AnalysisServices.XmlaReader.ReadStartElement(String localname, String ns)
   at Microsoft.AnalysisServices.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)
   --- End of inner exception stack trace ---
   at Microsoft.AnalysisServices.XmlaClient.SendMessage(Boolean endReceivalIfException, Boolean readSession, Boolean readNamespaceCompatibility)
   at Microsoft.AnalysisServices.Core.AnalysisServicesClient.Discover(IMajorObject obj, ObjectExpansion expansion, JaXmlSerializer serializer)
   at Microsoft.AnalysisServices.Core.Server.Refresh(IMajorObject obj, ObjectExpansion expansion)
   at Microsoft.AnalysisServices.Core.Server.SendRefresh(IMajorObject obj, ObjectExpansion expansion)
   at Microsoft.AnalysisServices.MajorObject.Refresh(ObjectExpansion expansion)
   at Microsoft.AnalysisServices.Core.Server.Connect(String connectionString, String sessionId, ObjectExpansion expansionType)
   at PbiTools.Deployments.DeploymentManager.DeployDatasetAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 108
   at PbiTools.Deployments.DeploymentManager.DeployAsync(String profileName, String environment) in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Deployments\DeploymentManager.cs:line 84
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Cli\Deploy.cs:line 41
--- End of stack trace from previous location ---
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\145-Parameters-v2\src\PBI-Tools\Program.cs:line 88`

**Comment by quinse** [comment]
fixed this issue by upgrading from 1.0.0-rc.2+20220703 to 1.0.0-rc.2+preview.5
