### ISSUE TITLE
PathTooLongException when extracting

### ISSUE THREAD

**Issue by magnusneck** [pbi-tools/pbi-tools#210]
Is there any way to customize the extract action to avoid PathTooLongException when you have long descriptive names of report items?

E.g:

PS C:\Repositories\Default\CFW.Dev\PBIX\CreditManagement> & $PbiTools extract .\CreditMonitoring.pbix
Using Power BI Desktop install: 2.110.1161.0 (22.10) at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.110.1161.0_x64__8wekyb3d8bbwe\bin
Extracting DataModel from PBIX
MSMDSRV.EXE found at C:\Users\magnec_admin\AppData\Local\pbi-tools\Microsoft.MicrosoftPowerBIDesktop_2.110.1161.0_x64__8wekyb3d8bbwe\msmdsrv.exe
Working directory: C:\Users\magnec_admin\AppData\Local\Temp\tmp27F6.tmp
Tabular Server process launched successfully. Port: 57469
Model image from PBIX loaded successfully.
Extracting PBIX file to: C:\Repositories\Default\CFW.Dev\PBIX\CreditManagement\CreditMonitoring
Version [1.22] extracted to: C:\Repositories\Default\CFW.Dev\PBIX\CreditManagement\CreditMonitoring\Version.txt
An unhandled exception occurred.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at PbiTools.FileSystem.ProjectFolder.WriteFile[T](String path, Func`2 factory, Action`1 callback) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 141
   at PbiTools.FileSystem.ProjectFolder.WriteText(String path, Action`1 onTextWriterAvailable) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 137
   at PbiTools.Utils.JsonExtensions.ExtractAndParseTokenAs[T](JObject parent, String property, IProjectFolder folder) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Utils\JsonExtensions.cs:line 71
   at PbiTools.Serialization.ReportSerializer.Serialize(JObject content) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Serialization\ReportSerializer.cs:line 97
   at PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Model\PbixModel.cs:line 276
   at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Nullable`1 pid, Nullable`1 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSe
rializationMode mashupSerialization, Boolean watch) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Cli\Extract.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in B:\DEV\mt\GitHub\pbi-tools-preview.4\src\PBI-Tools\Program.cs:line 94

**Comment by mthierba** [comment]
Duplicate: #56
