### ISSUE TITLE
SqlScripts connection to SQL Server fails after upgrade to RC.2

### ISSUE THREAD

**Issue by mthierba** [pbi-tools/pbi-tools#230]
```
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. (Failed to connect to the SqlScripts database: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught))
 ---> PbiTools.Deployments.DeploymentException: Failed to connect to the SqlScripts database: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
   at PbiTools.Deployments.SqlScriptsDeployer.TestConnection() in X:\src\pbi-tools\src\PBI-Tools\Deployments\SqlScriptsDeployer.cs:line 82
   at PbiTools.Deployments.DeploymentManager.DeployDatasetAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 173
   at PbiTools.Deployments.DeploymentManager.DeployAsync(String profileName, String environment) in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.cs:line 84
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\src\pbi-tools\src\PBI-Tools\Cli\Deploy.cs:line 41
--- End of stack trace from previous location ---
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\src\pbi-tools\src\PBI-Tools\Program.cs:line 89
```

**Comment by mthierba** [comment]
This is caused by the switch from `System.Data.SqlClient` to `Microsoft.Data.SqlClient`. The latter enforces stronger security requirements.

See dotnet/SqlClient#1479.

Workaround: Add `Encrypt=false` to the connection string (assuming that behavior is desired).

This can be added to the deployment manifest like so:

```
{
  "version": "0.12",
  "deployments": {
    "Dataset": {
      "options": {
        "sqlScripts": {
          "enabled": true,
          "schema": "{{[Schema]}}",
          "path": "./Views",
          "connection": {
            "Server": "{{[SQL Server]}}",
            "Initial Catalog": "{{[Database]}}",
            "User ID": "%SQL_USERNAME%",
            "Password": "%SQL_PWD%",
            "Encrypt": "false"
          }
        }
      }
    }
  }
}
```
