### ISSUE TITLE
`PowerBIModelNotFoundException` error when deploying report

### ISSUE THREAD

**Issue by bentocin** [pbi-tools/pbi-tools#235]
I was following the demo repo [report-devops-demo](https://github.com/pbi-tools/report-devops-demo). I exchanged the `manifest.authentication` with my own service principal credentials. I also changed `source.path` to only use `./Report` folder. However, when I run `pbi-tools deploy  . Reports` I always get a `BadRequest` error stating `PowerBIModelNotFoundException`.

I couldn't really figure out yet what is causing that problem.

When following the [dataset-devops-demo](https://github.com/pbi-tools/dataset-devops-demo) the dataset and report can be deployed successfully.

See some more details below:

```json
# .pbixproj.json
{
  "version": "0.12",
  "deployments": {
    "Reports": {
      "mode": "Report",
      "source": {
        "type": "Folder",
        "path": "./Report"
      },
      "authentication": {
        "type": "ServicePrincipal",
        "tenantId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
        "clientId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
        "clientSecret": "%PBI_CLIENT_SECRET%"
      },
      "options": {
        "import": {
          "nameConflict": "CreateOrOverwrite"
        }
      },
      "environments": {
        "Development": {
          "workspace": "Reports DevOps [DEV]"
        },
        "Staging": {
          "workspace": "Reports DevOps [UAT]"
        },
        "Production": {
          "workspace": "Reports DevOps"
        }
      }
    }
  }
}
```

<details>
<summary>Result running pbi-tools deploy</summary>

```sh
$ pbi-tools deploy reports/ Reports
Reading PBIXPROJ settings from: C:\Users\XXX\Downloads\tacto-code\powerbi-reports\reports\.pbixproj.json
Starting deployment 'Reports' into environment: Development ...
Found 1 source folders to deploy.
Creating PBIX from report source at: 'C:\Users\XXX\AppData\Local\Temp\XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\Report.pbix'...
Reading PBIXPROJ settings from: C:\Users\XXX\Downloads\tacto-code\powerbi-reports\reports\Report\.pbixproj.json
Using Power BI Desktop install: 2.112.1161.0 (22.12) at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.112.1161.0_x64__8wekyb3d8bbwe\bin
Generating PBIX file at 'C:\Users\XXX\AppData\Local\Temp\XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\Report.pbix'...
Access token received. Expires On: 01/25/2023 10:53:02 +00:00
Resolved workspace ID 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' for workspace: 'Reports DevOps [DEV]'
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. ---> PbiTools.Deployments.DeploymentException: HTTP Error: BadRequest
{
  "error": {
    "code": "PowerBIModelNotFoundException",
    "pbi.error": {
      "code": "PowerBIModelNotFoundException",
      "parameters": {},
      "details": [],
      "exceptionCulprit": 1
    }
  }
} ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.PowerBI.Api.ImportsOperations.<UploadFile>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.ImportsOperations.<PostImportFileWithHttpMessage>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.ImportsOperationsExtensions.<PostImportWithFileAsyncInGroup>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<ImportReportAsync>d__45.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 302
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PbiTools.Deployments.DeploymentManager.<DeployReportAsync>d__38.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 99
   --- End of inner exception stack trace ---
   at PbiTools.Deployments.DeploymentManager.<DeployReportAsync>d__38.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.cs:line 81
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\src\pbi-tools\src\PBI-Tools\Cli\Deploy.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\src\pbi-tools\src\PBI-Tools\Program.cs:line 95
---> (Inner Exception #0) PbiTools.Deployments.DeploymentException: HTTP Error: BadRequest
{
  "error": {
    "code": "PowerBIModelNotFoundException",
    "pbi.error": {
      "code": "PowerBIModelNotFoundException",
      "parameters": {},
      "details": [],
      "exceptionCulprit": 1
    }
  }
} ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.PowerBI.Api.ImportsOperations.<UploadFile>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.ImportsOperations.<PostImportFileWithHttpMessage>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerBI.Api.ImportsOperationsExtensions.<PostImportWithFileAsyncInGroup>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<ImportReportAsync>d__45.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 302
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PbiTools.Deployments.DeploymentManager.<DeployReportAsync>d__38.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 99
   --- End of inner exception stack trace ---
   at PbiTools.Deployments.DeploymentManager.<DeployReportAsync>d__38.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.cs:line 81<---
```
</details>

<details>
<summary>`pbi-tools info` output</summary>

```sh
$ pbi-tools info
{
  "version": "1.0.0-rc.2",
  "edition": "Desktop",
  "build": "1.0.23009.2256",
  "pbixProjVersion": "0.12",
  "pbiBuildVersion": "2.112.603.0",
  "longPathsEnabled": false,
  "amoVersion": "19.54.1.0",
  "toolPath": "C:\\Users\\XXX\\Downloads\\pbi-tools.1.0.0-rc.2\\pbi-tools.exe",
  "locale": {
    "system": "de-DE (1031)",
    "ui": "en-US (1033)"
  },
  "settings": {
    "PBITOOLS_LogLevel": null,
    "PBITOOLS_PbiInstallDir": null,
    "PBITOOLS_AppDataDir": null,
    "PBITOOLS_Debug": null,
    "PBITOOLS_UICulture": null,
    "PBITOOLS_EffectiveDate": null
  },
  "runtime": {
    "platform": "Microsoft Windows 10.0.22621 ",
    "architecture": "X64",
    "framework": ".NET Framework 4.8.9105.0"
  },
  "pbiInstalls": [
    {
      "ProductVersion": "2.112.1161.0 (22.12)",
      "Is64Bit": true,
      "InstallDir": "C:\\Program Files\\WindowsApps\\Microsoft.MicrosoftPowerBIDesktop_2.112.1161.0_x64__8wekyb3d8bbwe\\bin",
      "SettingsDir": "C:\\Users\\XXX\\Microsoft\\Power BI Desktop Store App",
      "Location": "WindowsStore"
    }
  ],
  "effectivePbiInstallDir": "C:\\Program Files\\WindowsApps\\Microsoft.MicrosoftPowerBIDesktop_2.112.1161.0_x64__8wekyb3d8bbwe\\bin",
  "pbiSessions": []
}
```
</details>

**Comment by mthierba** [comment]
This happens when the service principal used to deploy a thin report does not have sufficient permissions on the linked dataset - it's very common, and it has happened to me a lot as well. Easy fix, thankfully.

**Comment by mthierba** [comment]
Here's a recorded demo for this exact repo: https://www.youtube.com/watch?v=mV3Gr2uov2w&list=PL4CLHO2g-2e7WRkyxQFPF90tChO9rBXy3 (How to set it up in your own tenant.) Since it's a thin report, you'll need to make the dataset available first.

**Comment by bentocin** [comment]
First of all: Thanks for the quick response and sorry for my delayed one.

Your comments definitely helped solve the issue. After first uploading the dataset it worked perfectly fine. Maybe the other dataset that was mentioned in the connection was outdated and didn't exist anymore.
