### ISSUE TITLE
Error in calling pbi-tools extract

### ISSUE THREAD

**Issue by pjain00** [pbi-tools/pbi-tools#243]
I executed the following command

pbi-tools.exe extract ".\code\pbi_datasets\folder\xxxxxxxxxxxx.pbix" -extractFolder "C:\code\folder" -modelSerialization Raw 

And received following error:
[2023-02-23T07:10:44.203Z] An unhandled exception occurred.
[2023-02-23T07:10:44.203Z] System.IO.FileLoadException: Could not load file or assembly 'Microsoft.PowerBI.Packaging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e32' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)
[2023-02-23T07:10:44.203Z] File name: 'Microsoft.PowerBI.Packaging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e32' ---> System.Exception: No 64-bit Power BI Desktop installation found
[2023-02-23T07:10:44.203Z]    at PbiTools.Utils.DependenciesResolver.GetPBIInstall() in X:\src\pbi-tools\src\PBI-Tools\Utils\DependenciesResolver.cs:line 85
[2023-02-23T07:10:44.203Z]    at PbiTools.Utils.DependenciesResolver.GetEffectivePowerBiInstallDir() in X:\src\pbi-tools\src\PBI-Tools\Utils\DependenciesResolver.cs:line 193
[2023-02-23T07:10:44.203Z]    at PbiTools.Utils.DependenciesResolver.<>c__DisplayClass13_0.<AssemblyResolve>b__0(Object sender, ResolveEventArgs args) in X:\src\pbi-tools\src\PBI-Tools\Utils\DependenciesResolver.cs:line 100
[2023-02-23T07:10:44.203Z]    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
[2023-02-23T07:10:44.203Z]    at PbiTools.PowerBI.PbixReader..ctor(String pbixPath, IDependenciesResolver resolver)
[2023-02-23T07:10:44.203Z]    at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Nullable`1 pid, Nullable`1 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization, Boolean watch) in X:\src\pbi-tools\src\PBI-Tools\Cli\Extract.cs:line 83
[2023-02-23T07:10:44.203Z] --- End of stack trace from previous location where exception was thrown ---
[2023-02-23T07:10:44.203Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[2023-02-23T07:10:44.203Z]    at PowerArgs.ArgAction.Invoke()
[2023-02-23T07:10:44.203Z]    at PbiTools.Program.Main(String[] args) in X:\src\pbi-tools\src\PBI-Tools\Program.cs:line 95
[2023-02-23T07:10:44.203Z]

==============================

Although I have installed PowerBI desktop using the following script on my server:

https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases/download/3.9.2/PSAppDeployToolkit_v3.9.2.zip

**Comment by mthierba** [comment]
You either don't have the 64-bit version of PBI Desktop installed, or you didn't install it using the MSI or via the Windows Store. 

However, even if you used a custom install method for 64-bit PBI Desktop, you can still get it to work with `pbi-tools` by setting the `PBITOOLS_PbiInstallDir` environment variable to your installation folder. `pbi-tools` will then use PBI Desktop from that path.
