### ISSUE TITLE
Refresh failed because of missing credentials

### ISSUE THREAD

**Issue by ReaperGun** [pbi-tools/pbi-tools#248]
Hello, I wanted to start this by saying that you made a great and super useful tool to accomplish ci/cd of reports/datasets. It is also relatively easy to understand, however i have an issue right now when I deploy the dataset together with the report in power bi service using the refresh functionality so I can have the data in the dataset, the refresh fails giving me an error saying that I am missing credentials, I haven't found much documented about this and I am not sure what to do in this scenario because the report won't work unless the refresh is done from what I have seen.
![image](https://user-images.githubusercontent.com/81096826/223230650-7affa4c6-8ae1-4868-aca6-0f04a99f9aaf.png)
![image](https://user-images.githubusercontent.com/81096826/223230745-f82fbbe9-69a1-4ffc-90e6-63b6d049256f.png)

**Comment by mthierba** [comment]
Hi @ReaperGun ,

for dataset credentials, there are effectively three options:

1. Bind dataset to an Enterprise Gateway during `pbi-tools` deployment (fully supported, but only on initial creation of the dataset)
2. Set credentials during `pbi-tools` deployment (partially supported: username/password credentials only for now, more credential types to be added, see #195)
3. After initial `pbi-tools` dataset deployment, manually take over the dataset and set gateway/credentials via the UI (fully supported, but manual)

This sample project demonstrates how user/password cloud credentials are set via the manifest: https://github.com/pbi-tools/incremental-refresh-demo/blob/main/.pbixproj.json

The schema for binding to an existing gateway is this:
```json
{
    "options": {
        "dataset": {
            "gateway": {
                "gatewayId": "<GUID>",
                "discoverGateways": true,
                "dataSources": [
                    "dataSource1",
                    "dataSource2"
                ]
            }
        }
    }
}
```

That option uses this API under the hoods: https://learn.microsoft.com/en-gb/rest/api/power-bi/datasets/bind-to-gateway-in-group#example-with-'datasourceobjectids'

**Comment by ReaperGun** [comment]
Thank you, I will try the credentials version and i will let you know, I have one more question, if i publish the dataset together with the report and manually take over the dataset and refresh it, will I be able to also download the pbix file? Because for now when i try to download the published file I get an error saying that i can't download the file because  the dataset was altered through XMLA endpoint

**Comment by mthierba** [comment]
Dataset ownership does no impact whether or not the pbix can be downloaded. And, you don't even require that since with `pbi-tools` the source of truth is in your code repository, not in the PBI workspace, i.e. you always have a copy of the project files available to you in any case.
The related report, however, should always be downloadable - `pbi-tools` intentionally converts the report into "thin" report format, i.e. with a live connection to your dataset.

**Comment by ReaperGun** [comment]
Hello again, I tried to refresh the dataset using the credential method because this is the only possible way for my scenario but i still keep getting the same error regarding missing credentials
![Screenshot_20230309-110745~2](https://user-images.githubusercontent.com/81096826/223975466-20c50a50-71af-45f2-bc2f-853a36d05535.png)

![Screenshot_20230309-110729~2](https://user-images.githubusercontent.com/81096826/223975484-cf6a5831-f781-4c3d-a2ec-913723ca7b1f.png)
![Screenshot_20230309-110716~2](https://user-images.githubusercontent.com/81096826/223975507-e6da5959-6148-4e7e-95d9-ed59fb0df439.png)
![Screenshot_20230309-110638~2](https://user-images.githubusercontent.com/81096826/223975614-385b45cc-8373-404b-9de9-39882e549b80.png)

**Comment by mthierba** [comment]
Could you post the full deployment log? That's needed to be able to understand what's happening. Is it working when you deploy to a new location, instead of updating an existing dataset?

**Comment by ReaperGun** [comment]
System.AggregateException: One or more errors occurred. ---> PbiTools.Deployments.DeploymentException: Refresh failed because of missing credentials. See [https://docs.microsoft.com/power-bi/enterprise/service-premium-connect-tools#setting-data-source-credentials](https://docs.microsoft.com/power-bi/enterprise/service-premium-connect-tools?fbclid=IwAR3sZTgOz-m1lDNeTiWTWRdm75Wy0Trorwv7aSt7SbJ72hApd9TBXiiF6Gs#setting-data-source-credentials) for further details. ---> Microsoft.AnalysisServices.OperationException: Failed to save modifications to the server. Error returned: '{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}

Technical Details:
RootActivityId: fdf51358-795d-4b1a-8ca7-4dc0e17364b6
Date (UTC): 3/9/2023 5:21:11 PM
The current operation was cancelled because another operation in the transaction failed.
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
'.
   at Microsoft.AnalysisServices.Tabular.Model.SaveChangesImpl(SaveOptions options)
   at PbiTools.Deployments.XmlaRefreshManager.RunRefresh() in X:\src\pbi-tools\src\PBI-Tools\Deployments\XmlaRefreshManager.cs:line 96
   --- End of inner exception stack trace ---
   at PbiTools.Deployments.XmlaRefreshManager.RunRefresh() in X:\src\pbi-tools\src\PBI-Tools\Deployments\XmlaRefreshManager.cs:line 112
   at PbiTools.Deployments.DeploymentManager.<DeployDatasetAsync>d__32.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 449--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.cs:line 84
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\src\pbi-tools\src\PBI-Tools\Cli\Deploy.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\src\pbi-tools\src\PBI-Tools\Program.cs:line 95
---> (Inner Exception #0) PbiTools.Deployments.DeploymentException: Refresh failed because of missing credentials. See [https://docs.microsoft.com/power-bi/enterprise/service-premium-connect-tools#setting-data-source-credentials](https://l.facebook.com/l.php?u=https%3A%2F%2Fdocs.microsoft.com%2Fpower-bi%2Fenterprise%2Fservice-premium-connect-tools%3Ffbclid%3DIwAR0amCWwjTFETwCxL7T78fDHc5N-HN0aIJeaT8MZ9_7rarjtayGWYaz_cxg%23setting-data-source-credentials&h=AT1uGM_YBajVPT8xTtu3ohMnOGzk6weu3mCn8-kahAnVCqsMKjalyHjuDLs1NkixLZeHc_KbKzbw17ch4lPXU_-z6sIxku4G9MR0a--IkjLRm7dCYk18OEVW02fS5fglfdnWLajKUfh6XURO7rrC8w) for further details. ---> Microsoft.AnalysisServices.OperationException: Failed to save modifications 
to the server. Error returned: '{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}

Technical Details:
RootActivityId: fdf51358-795d-4b1a-8ca7-4dc0e17364b6
Date (UTC): 3/9/2023 5:21:11 PM
The current operation was cancelled because another operation in the transaction failed.
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
{"error":{"code":"DMTS_DatasourceHasNoCredentialError","pbi.error":{"code":"DMTS_DatasourceHasNoCredentialError","details":[{"code":"Server","detail":{"type":1,"value":"testserver.database.windows.net"}},{"code":"Database","detail":{"type":1,"value":"testdb"}},{"code":"ConnectionType","detail":{"type":0,"value":"Sql"}}],"exceptionCulprit":1}}}
'.
   at Microsoft.AnalysisServices.Tabular.Model.SaveChangesImpl(SaveOptions options)
   at PbiTools.Deployments.XmlaRefreshManager.RunRefresh() in X:\src\pbi-tools\src\PBI-Tools\Deployments\XmlaRefreshManager.cs:line 96
   --- End of inner exception stack trace ---
   at PbiTools.Deployments.XmlaRefreshManager.RunRefresh() in X:\src\pbi-tools\src\PBI-Tools\Deployments\XmlaRefreshManager.cs:line 112
   at PbiTools.Deployments.DeploymentManager.<DeployDatasetAsync>d__32.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 449--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.cs:line 84<---

**Comment by mthierba** [comment]
This is for a cloud SQL Server, presumably Azure Sql? If it were on-prem SQL, you'd have to connect via an enterprise gateway, of course. Unfortunately, you posted the error message, not the deployment log, so I still can't tell what happened at the stage of the deployment where credentials would be set.

**Comment by ReaperGun** [comment]
Yea, I use an Azure SQL Server connection

**Comment by ReaperGun** [comment]
Setting model expression 'Database'
        Old value: "TestDB1" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]
        New value: "TestDB"
Found existing dataset. 
TOM Database Properties:
* ID                    : d9df48a8-8c4b-4c1c-99ec-f25368033bc4
* Name                  : Employee Performance
* Description           : 
* CompatibilityLevel    : 1550
* CreatedTimestamp      : 03/09/2023 09:10:21
* StructureModifiedTime : 03/09/2023 07:10:30
* EstimatedSize         : 711464
Update Results:

Model deployment succeeded.

Power BI Dataset Details:
* ID                     : d9df48a8-8c4b-4c1c-99ec-f25368033bc3
* Name                   : Employee Performance
* WebUrl                 : url
* ConfiguredBy           : casian.stefan
* CreatedDate            : 03/09/2023 07:10:20
* IsRefreshable          : True
* IsOnPremGatewayRequired: False
* TargetStorageMode      : Abf
Datasources:
┌────────────────┬──────────────────────────────────────────────────────────────────┬──────────────────────────────────────┬──────────────────────────────────────┐  
│ DatasourceType │ ConnectionDetails                                                │ DatasourceId                         │ GatewayId                            │  
├────────────────┼──────────────────────────────────────────────────────────────────┼──────────────────────────────────────┼──────────────────────────────────────┤  
│ Sql            │ {"server":"testserver.database.windows.net","database":"testdb"} │ 0895afb2-63fa-4ac7-bd35-5eaa64e78592 │ 6e7c91fb-79e9-4cb3-9a66-f115c897e093 │  
└────────────────┴──────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┘  
Generating report connections file from embedded default template.
Creating PBIX from report source at: 'C:\Users\casian.boska\AppData\Local\Temp\f924e0df-472d-4bc4-8cfa-2236ed48da0c\Employee Performance.pbix'...
Reading PBIXPROJ settings from: C:\Users\casian.stefan\Desktop\AzureDevops playground\Training\Reportsv2\Employee Performance\.pbixproj.json
Generating PBIX file at 'C:\Users\casian.stefan\AppData\Local\Temp\f924e0df-472d-4bc4-8cfa-2236ed48da0c\Employee Performance.pbix'...
Import: Employee Performance.pbix, State: Publishing (Id: 61dd1e87-7fd4-4fbd-8fcd-a00707ec7ed2)
Import succeeded: 61dd1e87-7fd4-4fbd-8fcd-a00707ec7ed2 (Employee Performance.pbix)
        Report: 9a5fe848-719e-4c57-a623-92c0e0a49625 "Employee Performance"
        Url: url
Report Created: 03/09/2023 07:10:35
Report Updated: 03/09/2023 18:50:32
Starting dataset refresh (Full) ...
Using default refresh type: Full
Refreshing model (Full)...

**Comment by mthierba** [comment]
`pbi-tools` will fetch the datasources configured against the dataset in PBI Model, and will then aim to match the connection details against what you have specified under credentials/match. 
Based on your screenshot above, in your case it will need to match type = `Sql` and `{"server":"testserver.database.windows.net","database":"testdb"}`.

If there is a match, this message will be shown in the logs:

> Matched remote datasource {Type}: {ConnectionDetails} ({DatasourceId})

Next, _UpdateMode_ is evaluated. It can be:
* NotSpecified _(Sets creds only if the datasource doesn't already have credentials)_
* Always _(Always sets credentials)_
* Never _(Does nothing)_

If the datasource is skipped in `NotSpecified` mode, this message is printed:

> - Skipping datasource because UpdateMode is set to 'NotSpecified' and credential type is {CredentialType}.

If you see non of those messages it must be because none of the datasources could be matched against your parameters.

In your case the environment variable `ServerName` must be set to "testserver.database.windows.net", and the `DatabaseName` variable needs to be set to "testdb" for this to work. That's because you are using ENV references in the match. To debug this, you could remove the variables and simply insert the plain values there, removing one potential hiccup.

**Comment by ReaperGun** [comment]
Hello, i managed to find the issue, apparently from what I have seen just now, `pbi-tools` changes my database name to lowercase, meaning if i enter  the value `TestDB` to the `Database` parameter, it will be changed in the in this section to testdb ┌────────────────┬──────────────────────────────────────────────────────────────────┬──────────────────────────────────────┬──────────────────────────────────────┐
│ DatasourceType │ ConnectionDetails │ DatasourceId │ GatewayId │
├────────────────┼──────────────────────────────────────────────────────────────────┼──────────────────────────────────────┼──────────────────────────────────────┤
│ Sql │ {"server":"testserver.database.windows.net","database":"testdb"} │ 0895afb2-63fa-4ac7-bd35-5eaa64e78592 │ 6e7c91fb-79e9-4cb3-9a66-f115c897e094 │
└────────────────┴──────────────────────────────────────────────────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┘

However, the value that i entered in my connection was `{"server":"testserver.database.windows.net","database":"TestDB"}` instead of testdb, and it seems to be case sensitive which causes the match issue i guess, once i changed the name of the database to testdb, everything worked fine, any idea why pbi-tools converts the value to lowercase?

**Comment by mthierba** [comment]
`pbi-tools` currently performs a case-sensitive comparison, and this: `{"server":"testserver.database.windows.net","database":"testdb"}` is how PBI has stored your datasource information - I'm assuming those details always get normalized on the server.

That's why `pbi-tools` displays the data source table in the logs, so you understand which values you need to match.

Incidentally, I left a comment in the source code noting that a case-insensitive comparison might be safer here:

https://github.com/pbi-tools/pbi-tools/blob/b02640e6775c16ce59aced02c88bd16e5c2cb2af/src/PBI-Tools/Deployments/DatasetCredentialsManager.cs#L113-L119

Will add that to the backlog.

**Comment by ReaperGun** [comment]
I understand, thanks for all the help here, and for clearing things up for me

**Comment by ReaperGun** [comment]
Hello again, sorry to keep closing and reopening this issue, however, something weird is happening that is related to the same error that I am getting, I am now trying to use parameters for the server and database in the credentials match part, however seems that I get the same error and I don't get the following message:
Matched remote datasource {Type}: {ConnectionDetails} ({DatasourceId})
I think this means that it doesn't match, do variables in devops not work for this?

**Comment by ReaperGun** [comment]
I forgot to mention that the time when I said that it worked, i only tested it locally, running the pbi-tools deploy from vs code, once I began using the ENV variables in Azure Devops it no longer worked to refresh

**Comment by mthierba** [comment]
@ReaperGun  Would you be able to share your manifest here? (Remove anything sensitive, of course.) It's hard to provide help w/o anything concrete to look at.

**Comment by turnersale** [comment]
If you would like, I actually have a PowerShell script that uses the same service principal that we use for automated deployments to assume ownership of all reports in a workspace and (or multiple) and update the credentials so refresh schedules can work as expected. It uses the PBI APIs and Azure DevOps secrets passed as envars and works pretty well (might need some more tweaks). It actually has a nice side-effect of forcing devs to only use supported datasets (since they would have to manually take over a dataset otherwise) which allows us to improve our security and standardization. Happy to share if you want to compare and/or if you haven't found a solution already.

**Comment by christoffp** [comment]
@mthierba - is it possible to set the credentials of a Sql datasource type to use a Service Pincipal? This is what I've been trying without success:
      "credentials": [
        {
          "match": {
            "datasourceType": "Sql",
            "connectionDetails": {
              "server": "tcp:blah-blah-ondemand.sql.azuresynapse.net,1433",
              "database": "BlahBlah"
            }
          },
          **"type": "ServicePrincipal",**

**Comment by NPissarra** [comment]
Hi,

I would like to set automaticaly the refresh credentials for a link on the web, when I deploy my dataset.
Manually I whould do it in the settings for the dataset:

![image](https://github.com/user-attachments/assets/2f7aff39-cb61-4f9a-8fbb-b2ca73304856)

Can you help me to identify witch parameters I should use in the schema, like you did in this previous comment: https://github.com/pbi-tools/pbi-tools/issues/248#issuecomment-1458552319

![image](https://github.com/user-attachments/assets/33cc64f0-cd00-4208-9f21-fed8b85b372a)

Thanks!

**Comment by mthierba** [comment]
You can use this example manifest as a template: https://github.com/pbi-tools/pbi-tools/blob/main/tests/projects/tmdl-deploy/.pbixproj.json

1. Grab the data source type & details from your deployment logs (ex: https://github.com/pbi-tools/pbi-tools/actions/runs/11561581572/job/32180902324#step:8:123)
2. Insert a [`credentials` section](https://github.com/pbi-tools/pbi-tools/blob/main/tests/projects/tmdl-deploy/.pbixproj.json#L16-L27); ensure the datasource connection details match the ones in your model
4. Enable [credential updating](https://github.com/pbi-tools/pbi-tools/blob/main/tests/projects/tmdl-deploy/.pbixproj.json#L57)

# Allowed values for UpdateMode

* NotSpecified
* Always
* Never
* BeforeRefresh

# Allowed values for CredentialType

* Basic
* Anonymous
* OAuth2
