### ISSUE TITLE
Is there a way to connect to Gov cloud instead of Commercial?

### ISSUE THREAD

**Issue by dllcons** [pbi-tools/pbi-tools#252]

**Comment by mthierba** [comment]
Yes, that is indeed supported. You can set manifest.authentication.authority (an alternative to tenantId) for complete control of authentication, as well as manifest.options.pbiBaseUri to use an alternative PBI API endpoint.

**Comment by cubdevmdc** [comment]
Thanks for the suggestion @mthierba, I followed it and modify my _.pbixproj.json_ file as below:
`{
  "version": "0.12",
  "created": "2023-03-18T17:55:55.0351854-04:00",
  "lastModified": "2023-03-18T17:55:55.2448623-04:00",
  "deployments": {
    "Files": { //Profile variable
      "mode": "Report",
      "source": {
        "type": "File",
        "path": "./*.pbix$"
      },
      "authentication": {
        "type": "ServicePrincipal",
        "authority": "https://login.microsoftonline.com/my-tenantID",
        //"tenantId": "my-tenantID",
        "clientId": "my-clientID, // This is the client ID of the service principal
        "clientSecret": "#{my-secret}#" // This is the client secret of the service principal
      },
      "options": {
        "pbiBaseUri": "https://app.powerbigov.us",
        "import": {
          "nameConflict": "CreateOrOverwrite"
        }
      },
      "environments": {
        "DEV": { // This is the name of the environment you want to deploy to
          "workspace": "my-workspaceID" // This is the name of the workspace you want to deploy to
        }
      }
    }
  }
}`
Testing the deploy command with -whatIF yields this results:
_=== Deployment WhatIf mode enabled ===
Starting deployment 'Files' into environment: DEV ...
Determining reports from File source: "./*.pbix$"
Base folder: /__w/1/s
Found 1 source files to deploy.
Acquiring access token...
Token Endpoint: https://login.microsoftonline.com/my-tanantID/oauth2/v2.0/token
Access token received. Expires On: 04/04/2023 22:37:19 +00:00
---
Report: /__w/1/s/test-dataset.pbix
  DisplayName: test-dataset.pbix
  Parameters:
  * ENVIRONMENT = "DEV"
  * PBITOOLS_VERSION = "1.0.0-rc.2"
  * FILE_NAME = "test-dataset.pbix"
  * FILE_NAME_WITHOUT_EXT = "test-dataset"
  * FILE_PATH = "test-dataset.pbix"
  * MATCH_1 = "test-dataset"
  Workspace: my-workspaceID
---
Deployment completed successfully.
=== Deployment WhatIf mode enabled ===
Finishing: pbi-tools deploy -whatIf_

But when I run the deploy command, itself yields this error:
_Generating script.
Script contents:
/app/pbi-tools/pbi-tools.core deploy . "Files" "DEV"
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /__w/_temp/0689872b-23eb-4a54-886a-81f3f33e67a0.sh
Reading PBIXPROJ settings from: /__w/1/s/.pbixproj.json
Starting deployment 'Files' into environment: DEV ...
Found 1 source files to deploy.
Access token received. Expires On: 04/04/2023 22:37:21 +00:00
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. (Operation returned an invalid status code 'InternalServerError')
 ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'InternalServerError'
   at Microsoft.PowerBI.Api.ImportsOperations.UploadFile(Nullable`1 groupId, Stream file, String datasetDisplayName, Nullable`1 nameConflict, Nullable`1 skipReport, Nullable`1 overrideReportLabel, Nullable`1 overrideModelLabel, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.PowerBI.Api.ImportsOperations.PostImportFileWithHttpMessage(Nullable`1 groupId, Stream file, String datasetDisplayName, Nullable`1 nameConflict, Nullable`1 skipReport, Nullable`1 overrideReportLabel, Nullable`1 overrideModelLabel, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.PowerBI.Api.ImportsOperationsExtensions.PostImportWithFileAsyncInGroup(IImportsOperations operations, Guid groupId, Stream fileStream, String datasetDisplayName, Nullable`1 nameConflict, Nullable`1 skipReport, Nullable`1 overrideReportLabel, Nullable`1 overrideModelLabel, CancellationToken cancellationToken)
   at PbiTools.Deployments.DeploymentManager.ImportReportAsync(ReportDeploymentInfo args, IPowerBIClient powerbi, String workspace, IDictionary`2 workspaceIdCache) in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 302
   at PbiTools.Deployments.DeploymentManager.DeployReportAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 99
   at PbiTools.Deployments.DeploymentManager.DeployAsync(String profileName, String environment) in X:\src\pbi-tools\src\PBI-Tools\Deployments\DeploymentManager.cs:line 81
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\src\pbi-tools\src\PBI-Tools\Cli\Deploy.cs:line 41
--- End of stack trace from previous location ---
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\src\pbi-tools\src\PBI-Tools\Program.cs:line 89
##[error]Bash exited with code '247'._

**Comment by mthierba** [comment]
`login.microsoftonline.com` is the public cloud Auth endpoint. For US Gov, you need to use `https://login.microsoftonline.us`

See: https://learn.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud

**Comment by cubdevmdc** [comment]
Thanks for the suggestion @mthierba, after communicating with our admins he pointed out that our authentication Authority is under Commercial (will use `login.microsoftonline.com`) but our PBI lives under GCC, which is the standard setup of any Office 365 GCC costumers, and I believe the issue in question is related to that as I can authenticate correctly but cannot deploy my datasets. Any help is appreciated.

**Comment by mthierba** [comment]
Can you use the PS cmdlets for Power BI with your setup? Those ones are provided by Microsoft directly, and use the same setup as what I suggested.

The error message you provided indicates that whilst you are able to retrieve an access token from login.microsoftonline.com, that token is not authorized to perform the deployment operation.

Which suggests that either the token is insufficient (from the wrong authority?), or the related service principal does not have the required permissions. Does your service principal have at least Contributor access on your target workspace, and did you authorize the service principal in your Power BI tenant admin settings?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cubdevmdc** [comment]
Hi, @mthierba great suggestion I'm gonna run some cmdlets for Power BI using the same authentication as my setup. According to my admin the SP I'm using has been added to the workspace with admin permissions, as well as to the group on my Tenant level, but I will confirm with him again once I have run the cmdlets.
Thanks again.

**Comment by cubdevmdc** [comment]
As an update I ran a couple of tests using the cmdlets and I was able to run the following command:

`Connect-PowerBIServiceAccount -Tenant myTenantID -ServicePrincipal -Credential (Get-Credential) -Environment USGov`

After successful authentication I was able to run a deploy test to a workspace where the SP has permissions:
`$dataset = New-PowerBIDataSet -Name SampleDataSet -Tables $table1,$table2`
`Add-PowerBIDataSet -DataSet $dataset -WorkspaceId myWorkspaceId`

Now, what settings should I use in my _.pbixproj.json_ to achieve the same result?
