### ISSUE TITLE
An unhandled exception occurred while compiling to an opened file

### ISSUE THREAD

**Issue by R1k91** [pbi-tools/pbi-tools#272]
if you run the following command

`pbi-tools compile -folder "<folder>" -outPath "<outputfolder>" -format "PBIX"  -overwrite $true`

and the pbix already exists and it's opened you get and An unhandled exception.

An unhandled exception occurred.
System.IO.IOException: The process cannot access the file '.\Statistics - Copy.pbix' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at PbiTools.PowerBI.PbiPackage.Save(String path) in C:\src-tmdl\pbi-tools-tmdl\src\PBI-Tools\PowerBI\PbixWriter.cs:line 117
   at PbiTools.Cli.CmdLineActions.CompilePbix(String folder, String outPath, PbiFileFormat format, Boolean overwrite) in C:\src-tmdl\pbi-tools-tmdl\src\PBI-Tools\Cli\Compile.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in C:\src-tmdl\pbi-tools-tmdl\src\PBI-Tools\Program.cs:line 95

**Comment by mthierba** [comment]
It is expected that a write operation fails if the destination file is open in another application. That's standard operating system behavior. Are you asking for a more descriptive error message?

**Comment by R1k91** [comment]
I know it's by design, just pointing out it's unhandled and therefore you get stack trace output that maybe it's not so user friendly.

**Comment by mthierba** [comment]
The RC.4 release (https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-rc.4) introduces the notion of "known" exceptions: Those ones will only display the error message, but not the stack trace. So far, only the particular case you raised is handled that way.

The output now consists of a single line:

```
The operation FAILED: The process cannot access the file 'X:\temp\rc.4-testing\contoso-thin.pbix' because it is being used by another process.
```
