### ISSUE TITLE
An unhandled exception occurred during deserialization.

### ISSUE THREAD

**Issue by dennisate** [pbi-tools/pbi-tools#273]
I'm getting the error below compiling a thick report to a PBIT.  Is this issue caused by an updated version of PBI Desktop?  I was on 2.115.663.0 previously and it was working okay.

I'm on pbi-tools (Desktop), 1.0.0-rc.3 

pbi-tools extract "pl-900.pbix" -extractfolder ".\test" -modelSerialization TMDL
pbi-tools compile ".\test" -format PBIT -outPath "test.pbit" -overwrite

Using Power BI Desktop install: 2.116.763.0 (23.04) at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.116.763.0_x64__8wekyb3d8bbwe\bin
An unhandled exception occurred during deserialization.
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.AnalysisServices.Tabular.Tmdl.ReflectionPropertyConverter.FindHierarchy(MetadataObject metadataObject, String hierarchyName, String tableName)
   at Microsoft.AnalysisServices.Tabular.Tmdl.ReflectionPropertyConverter.SetModelRefProperty(Object instance, MetadataObject metadataObject, TmdlProperty property)
   at Microsoft.AnalysisServices.Tabular.Tmdl.ReflectionPropertyConverter.SetProperty(Object instance, TmdlProperty property, MetadataObject metadataObject, IDeferredPropertiesRegistry deferredProperties)
   at Microsoft.AnalysisServices.Tabular.Tmdl.BaseMetadataObjectConverter.<>c__DisplayClass28_0.<FromTMDL>b__2(ValueTuple`3 p)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Microsoft.AnalysisServices.Tabular.Tmdl.BaseMetadataObjectConverter.FromTMDL(TmdlObject tmdlObject, MetadataObject parent, MetadataObject existingInstance, IDeferredPropertiesRegistry deferredProperties, ITmdlSort sortImplementation)
   at Microsoft.AnalysisServices.Tabular.Tmdl.ModelConverter.FromTMDL(TmdlObject tmdlObject, MetadataObject parent, MetadataObject existingInstance, IDeferredPropertiesRegistry deferredProperties, ITmdlSort sortImplementation)
   at Microsoft.AnalysisServices.Tabular.TmdlSerializer.FromTMDL(TmdlProject tmdlProject, IMetadataObjectConverter modelConverter, MetadataObject existingInstance)
   at PbiTools.Serialization.TabularModelSerializer.DeserializeTmdl() in C:\src-tmdl\pbi-tools-tmdl\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 531
   at PbiTools.Serialization.TabularModelSerializer.TryDeserialize(JObject& database) in C:\src-tmdl\pbi-tools-tmdl\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 458
   at PbiTools.Serialization.PowerBIPartSerializerExtensions.DeserializeSafe[T](IPowerBIPartSerializer`1 serializer, Boolean isOptional) in C:\src-tmdl\pbi-tools-tmdl\src\PBI-Tools\Serialization\IPowerBIPartSerializer.cs:line 41

**Comment by mthierba** [comment]
This is a limitation in the TMDL Preview-1 release, judging from the stack trace related to perspectives.

You can either switch back to the Legacy serialization format, wait until the TMDL Preview-2, or drop perspectives from you model.

**Comment by dennisate** [comment]
I can confirm that using legacy for extract format as a workaround worked.

However, I've also found that turning off auto date/time will also work with TMDL.  I don't use perspectives on the model.

**Comment by mthierba** [comment]
This has been fixed in the upcoming Preview 2 of TMDL, expected in May.

**Comment by mthierba** [comment]
Fixed in TMDL Preview-2, which is included in https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-rc.4
