### ISSUE TITLE
Get an unhandled exception occurred. System.AggregateException for report only deployment

### ISSUE THREAD

**Issue by 9pr19** [pbi-tools/pbi-tools#282]
Hello @mthierba ,

I’m trying to deploy a report only project but I get the below error. 
The error seems to occur at line 143 in DeploymentManager.Report.cs .
But I can’t understand the code it’s too complicated for me ^^

I’ve watched your video https://www.youtube.com/watch?v=mV3Gr2uov2w .
And I’ve already successfully deployed a full report with pbi-tools (not this one).

Thank you in advance for your help :)

```
{
  "version": "0.12",
  "created": "2023-05-11T17:08:06.5228488+02:00",
  "lastModified": "2023-05-11T17:08:11.3874732+02:00",
  "settings": {
    "model": {
      "serializationMode": "Raw"
    },
    "mashup": {
      "serializationMode": "Raw"
    }
  },
  "deployments": {
    "Report": {
      "mode": "Report",
      "source": {
        "type": "Folder",
        "path": "."
      },
      "authentication": {
        "type": "ServicePrincipal",
        "tenantId": "%PBI_TENANT_ID%",
        "clientId": "%PBI_CLIENT_ID%",
        "clientSecret": "%PBI_CLIENT_SECRET%"
      },
      "options": {
        "import": {
          "nameConflict": "CreateOrOverwrite"
        }
      },
      "environments": {
        "UAT": {
          "workspace": "Report REC"
        },
        "PRD": {
          "workspace": "Report PRD"
        }
      }
    }
  }
}
```

```
$ /app/pbi-tools/pbi-tools.core deploy -folder "$report_folder" -label Report -environment $ENVIRONMENT -whatIf
Reading PBIXPROJ settings from: /builds/<myreportfolder>/.pbixproj.json
=== Deployment WhatIf mode enabled ===
Starting deployment 'Report' into environment: UAT ...
Determining reports from Folder source: "."
Base folder: /builds/<myreportfolder>
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'count'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'count')
   at System.Text.StringBuilder.Replace(String oldValue, String newValue, Int32 startIndex, Int32 count)
   at PbiTools.Deployments.DeploymentManager.ConvertSearchPatternToRegex(String pattern) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Deployments\DeploymentManager.cs:line 114
   at PbiTools.Deployments.DeploymentManager.ResolveSourceFolders(String path, String baseFolder, IDictionary`2 systemParameters) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 120
   at PbiTools.Deployments.DeploymentManager.GenerateReportsFromFolderSource(PbiDeploymentManifest manifest, PbiDeploymentEnvironment environment, String baseFolder) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 225
   at PbiTools.Deployments.DeploymentManager.DeployReportAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 50
   at PbiTools.Deployments.DeploymentManager.DeployAsync(String profileName, String environment) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Deployments\DeploymentManager.cs:line 88
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Cli\Deploy.cs:line 41
--- End of stack trace from previous location ---
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Program.cs:line 104
```
![image](https://github.com/pbi-tools/pbi-tools/assets/25961602/08b3b5fb-351a-4a57-99de-9ef08edc6809)

**Comment by mthierba** [comment]
Hi @9pr19, using the same folder (`"path": "."`) for your project sources is not supported. Please keep your extracted report sources in a sub-folder, and maintain a separate `.pbixproj.json` file containing the deployment manifest in the parent, with a `"path": "./{SUB-FOLDER}"` reference. See this example: https://github.com/pbi-tools/devops-demo-report

**Comment by 9pr19** [comment]
@mthierba ,

This makes sense, I’ve updated the project following your recommendation and it’s working. Thank you very much for your time and work :)

For other users here is the configuration:
* At the root I have  .pbixproj.json, report_main (folder containing the project a thick report), report2 (folder containing the project of a thin report linked with dataset of the thick report)

```
{
  "version": "0.12",
  "created": "2023-05-11T17:08:06.5228488+02:00",
  "lastModified": "2023-05-11T17:08:11.3874732+02:00",
  "deployments": {
    "report_main": {
      "mode": "Dataset",
      "source": {
        "type": "Folder",
        "path": "./report_main"
      },
      "authentication": {
        "type": "ServicePrincipal",
        "tenantId": "%PBI_TENANT_ID%",
        "clientId": "%PBI_CLIENT_ID%",
        "clientSecret": "%PBI_CLIENT_SECRET%"
      },
      "options": {
        "refresh": {
          "enabled": true,
          "skipNewDataset": false,
          "method": "XMLA",
          "type": "Full",
          "tracing": {
            "enabled": true
          }
        },
        "import": {
          "nameConflict": "CreateOrOverwrite"
        },
        "dataset": {
          "replaceParameters": true,
          "deployEmbeddedReport": true
        }
      },
      "parameters": {
        "[Version]": "%TAG_VERSION%",
        "[Environment]": "{{ENVIRONMENT}}",
        "[PBITOOLS_VERSION]": "{{PBITOOLS_VERSION}}",
        "[GIT_BRANCH]": "%GIT_BRANCH_NAME%",
        "[GIT_PIPELINE]": "%GIT_PIPELINE%",
        "[GIT_SHA]": "%GIT_SHA%"
      },
      "environments": {
        "UAT": {
          "workspace": "Workspace UAT"
        },
        "PRD": {
          "workspace": "Workspace PRD"
        }
      }
    },
    "report2": {
      "mode": "Report",
      "source": {
        "type": "Folder",
        "path": "./report2"
      },
      "authentication": {
        "type": "ServicePrincipal",
        "tenantId": "%PBI_TENANT_ID%",
        "clientId": "%PBI_CLIENT_ID%",
        "clientSecret": "%PBI_CLIENT_SECRET%"
      },
      "options": {
        "import": {
          "nameConflict": "CreateOrOverwrite"
        }
      },
      "environments": {
        "UAT": {
          "workspace": "Workspace UAT"
        },
        "PRD": {
          "workspace": "Workspace PRD"
        }
      }
    }
  }
}
```
