### ISSUE TITLE
The reader's MaxDepth of 64 has been exceeded

### ISSUE THREAD

**Issue by scottstauffer-fc** [pbi-tools/pbi-tools#284]
We ran pbitools.exe extract Dashbord XXXX.pbix and we get this error message.

If I take the line 1 and replace the period, I have 62 rows... hmm... each one creates a depth in the indentation?  
Can we change the **_MaxDepth_** to 128? or 1024 or 8192? 

:)

An unhandled exception occurred.

Newtonsoft.Json.JsonReaderException: **_The reader's MaxDepth of 64 has been exceeded_**. Path '**bookmarks[18].explorationState.sections.ReportSection227598f4bf4b2761c77a.visualContainers.97e8dfb9dfbc662ad879.filters.byName.Filterf29b284743a718774aa2.filter.Where[0].Condition.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.And.Left.Not.Expression.Comparison.Left.Column.Expression**', line 1, position 1283486.

   at Newtonsoft.Json.JsonReader.Push(JsonContainerType value)

   at Newtonsoft.Json.JsonTextReader.ParseValue()

   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)

   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)

   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)

   at PbiTools.Utils.JsonExtensions.ExtractToken[T](JObject parent, String property, IProjectFolder folder)

   at PbiTools.Serialization.ReportSerializer.Serialize(JObject content)

   at PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings)

   at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Nullable`1 pid, Nullable`1 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization, Boolean watch)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at PowerArgs.ArgAction.Invoke()

   at PbiTools.Program.Main(String[] args)

**Comment by scottstauffer-fc** [comment]
Ah, it is configurable!
I'll have to beg and plead for someone to make this change to issue a pull request. 


### Maximum depth
The latest version of Newtonsoft.Json has a maximum depth limit of 64 by default. [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json) also has a default limit of 64, and it's configurable by setting [JsonSerializerOptions.MaxDepth](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.maxdepth#system-text-json-jsonserializeroptions-maxdepth).

If you're using System.Text.Json indirectly by using ASP.NET Core, the default maximum depth limit is 32. The default value is the same as for model binding and is set in the [JsonOptions class](https://github.com/dotnet/aspnetcore/blob/1f56888ea03f6a113587a6c4ac4d8b2ded326ffa/src/Mvc/Mvc.Core/src/JsonOptions.cs#L17-L20).

[Source - Microsoft Learn - .NET JSON Serialization](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-7-0#maximum-depth)

**Comment by scottstauffer-fc** [comment]
[Source - MaxDepth setting - Json.NET Documentation - newtonsoft.com](https://www.newtonsoft.com/json/help/html/MaxDepth.htm)

<html>
<body>


MaxDepth setting
--



</body>
</html>

This sample uses the [MaxDepth](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_MaxDepth.htm) setting to constrain JSON to a maximum depth when deserializing.

### Sample:
![image](https://github.com/pbi-tools/pbi-tools/assets/96283513/ea041b01-896a-4bd0-a223-9abd3018b2a7)

**Comment by scottstauffer-fc** [comment]
I think I found out where the change is needed - I just need to see what I can do make this happen!

![image](https://github.com/pbi-tools/pbi-tools/assets/96283513/7f4f44d0-0fbf-45be-a236-d971535c6632)

**Comment by mthierba** [comment]
@scottstauffer-fc Would you be able to provide an example with such a deeply nested filter definition?
