### ISSUE TITLE
Error handling groupByColumns in TMDL mode when extracting a PBIX that uses Field Parameters

### ISSUE THREAD

**Issue by thesockmonster2** [pbi-tools/pbi-tools#290]
I have a Power BI dataset which uses a field parameter so you can use a slicer to define hierarchies in visuals.

When running the Extract command in Legacy serialization mode, pbi-tools will happily extract the dataset and compile again into a pbit. However, when I use TMDL mode, I get the following error:

An unhandled exception occurred during deserialization.
Microsoft.AnalysisServices.Tabular.TomInternalException: An internal error has occured.
   at Microsoft.AnalysisServices.Tabular.Column.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.CalculatedTableColumn.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Table.<>c__DisplayClass149_0.<SerializeToJsonObject>b__6(Column obj)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator``2.MoveNext()
   at System.Linq.Buffer``1..ctor(IEnumerable``1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable``1 source)
   at Microsoft.AnalysisServices.Tabular.Table.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Model.<>c__DisplayClass245_0.<SerializeToJsonObject>b__6(Table obj)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator``2.MoveNext()
   at System.Linq.Buffer``1..ctor(IEnumerable``1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable``1 source)
   at Microsoft.AnalysisServices.Tabular.Model.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Database.SerializeToJsonObject(JsonObject result, SerializeOptions options)
   at Microsoft.AnalysisServices.Tabular.Database.SerializeToNewJsonObject(SerializeOptions options)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeDatabase(Database database, SerializeOptions options)
   at PbiTools.Serialization.TabularModelSerializer.DeserializeTmdl() in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 532
   at PbiTools.Serialization.TabularModelSerializer.TryDeserialize(JObject& database) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 458
   at PbiTools.Serialization.PowerBIPartSerializerExtensions.DeserializeSafe[T](IPowerBIPartSerializer``1 serializer, Boolean isOptional) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\IPowerBIPartSerializer.cs:line 41

I've narrowed the issue down to the column "Selected Dimension Fields"

This is the json file created in legacy mode:
	{
	"type": "calculatedTableColumn",
	"name": "Selected Dimension Fields",
	"dataType": "string",
	"isNameInferred": false,
	"isDataTypeInferred": true,
  "sourceColumn": "[Value1]",
  "summarizeBy": "none",
  "relatedColumnDetails": {
    "groupByColumns": [
      {
        "groupingColumn": "Selected Dimension Fields Fields"
      }
    ]
  },
  "annotations": [
    {
      "name": "SummarizationSetBy",
      "value": "Automatic"
    }
  ]
}

This is the TMDL file created for the table:

table 'Selected Dimension Fields'
	lineageTag: f5f34cfa-24c6-4f0f-82db-a2e85eddc980
	ordinal: 70

	partition 'Selected Dimension Fields-96b76a90-aa18-4c6d-a0df-586389b144a2' = Calculated
		mode: Import
		expression:=
			{
			    ("Financial Period", NAMEOF('Date'[Financial Period]), 0),
			    ("Sales Category", NAMEOF('Item'[Sales Category]), 1),
			    ("Sales Sub Category", NAMEOF('Item'[Sales Sub Category]), 2),
			    ("Item Group", NAMEOF('Item'[Item Group]), 3),
			    ("Item", NAMEOF('Item'[Item]), 4),
			    ("Site", NAMEOF('Location'[Site]), 5),
			    ("Location", NAMEOF('Location'[Location]), 6),
			    ("Invoice Customer", NAMEOF('Invoice Customer'[Invoice Customer]), 7),
			    ("Order Customer", NAMEOF('Order Customer'[Order Customer]), 8),
			    ("Sales Rep", NAMEOF('Order Customer'[Order Customer Sales Rep]), 9),
			    ("Species", NAMEOF('Item'[Species]), 10),
			    ("Sub Species", NAMEOF('Item'[Sub Species]), 11),
			    ("Maturity", NAMEOF('Item'[Maturity]), 12),
			    ("Model Group", NAMEOF('Item'[Model Group]), 13),
			    ("Form", NAMEOF('Item'[Form]), 14),
			    ("Line Of Business", NAMEOF('Order Customer'[Order Customer Line Of Business]), 15),
			    ("Statistics Group", NAMEOF('Order Customer'[Order Customer Statistics Group]), 16),
			    ("Customer Classification Group", NAMEOF('Order Customer'[Order Customer Classification Group]), 17),
			    ("Segment", NAMEOF('Order Customer'[Order Customer Segment]), 18),
			    ("Sub Segment", NAMEOF('Order Customer'[Order Customer Sub Segment]), 19),
			    ("Sales Pool", NAMEOF('Sales Pool'[Sales Pool]), 20),
			    ("CustTrans Sales Pool", NAMEOF('Cust Trans Sales Pool'[Sales Pool]), 21),
			    ("Company Chain", NAMEOF('Order Customer'[Order Customer Company Chain]), 22),
			    ("Invoice", NAMEOF('Invoice'[Invoice]), 23),
			    ("Tonnes Or Units", NAMEOF('Converted Unit'[Tonnes Or Units]), 24)
			}

	column 'Selected Dimension Fields Fields'
		dataType: String
		isHidden
		isNameInferred: false
		lineageTag: 20aa397b-6613-40c7-a12c-65c7fc60efb7
		sortByColumn: 'Selected Dimension Fields Order'
		sourceColumn: [Value2]
		summarizeBy: None

		annotation SummarizationSetBy = Automatic

		extendedProperty ParameterMetadata =
			{
			  "version": 3,
			  "kind": 2
			}

	column 'Selected Dimension Fields Order'
		dataType: Int64
		formatString:= 0
		isHidden
		isNameInferred: false
		lineageTag: 2d27066c-3583-445a-a945-d08606a8a8ee
		sourceColumn: [Value3]
		summarizeBy: Sum

		annotation SummarizationSetBy = Automatic

	column 'Selected Dimension Fields'
		dataType: String
		isNameInferred: false
		lineageTag: 5bdea68f-f319-47fa-8b4f-69554e7c473a
		relatedColumnDetails:
			groupByColumns:
			- groupingColumn: 'Selected Dimension Fields Fields'
		sourceColumn: [Value1]
		summarizeBy: None

		annotation SummarizationSetBy = Automatic

	annotation PBI_Id = 404f82c5b1b245a5ac25bf450bfb9885`

I believe the part that is not compiling properly is this section (as when I remove it pbi-tools can compile the PBIT but then when I then open it and get data the field parameter no longer works):

		relatedColumnDetails:
			groupByColumns:
			- groupingColumn: 'Selected Dimension Fields Fields'

Is this an issue you are aware of and if so is there a solution?

Best regards,
Ben

**Comment by mthierba** [comment]
Great timing - I am actually discussing this exact problem right now, as your issue is coming in. We had experienced it before. The problem is well understood, but we need to decide between three different fixes.
I can provide a quick hotfix on the `pbi-tools` side, however, with no dependency on any code changes by Microsoft. Coming later today!

**Comment by mthierba** [comment]
@thesockmonster2 Fix is available here: https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-rc.5%2Bpreview.1

**Comment by thesockmonster2** [comment]
Thank you very much @mthierba for the speedy fix
