### ISSUE TITLE
pbi-tools compiling error

### ISSUE THREAD

**Issue by qwertylogandi** [pbi-tools/pbi-tools#307]
I get

PbiTools.Serialization.PbixProjSerializationException: The PBIX part at 'C:\orion\IngestionFiles\PBI\PBI_VG\marketdata-Cloud\Version.txt' could not be deserialized and is marked as not optional.
   at PbiTools.Serialization.PowerBIPartSerializerExtensions.DeserializeSafe[T](IPowerBIPartSerializer`1 serializer, Boolean isOptional) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\IPowerBIPartSerializer.cs:line 52

While trying to compile.  What is possibly wrong?

**Comment by mfleifbrg** [comment]
Detected the same issue yesterday here...
Using following command: 
pbi-tools compile -folder "$folderpath" -outPath $outpath -overwrite -format "pbix"

```
An unhandled exception occurred during deserialization.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PbiTools.Utils.JsonExtensions.InsertTokenAsString[T](JObject parent, String property, T token) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Utils\JsonExtensions.cs:line 82
   at PbiTools.Utils.JsonExtensions.InsertObjectFromFile(JObject parent, IProjectFolder folder, String fileName, Func`3 extendObject) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Utils\JsonExtensions.cs:line 97
   at PbiTools.Serialization.ReportSerializer.DeserializeReportElement(IProjectFolder folder, String objectFileName, String childCollectionName, Func`2 childElementFactory, Func`3 extendConfig) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\ReportSerializer.cs:line 225
   at PbiTools.Serialization.ReportSerializer.TryDeserialize(JObject& part) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\ReportSerializer.cs:line 207
   at PbiTools.Serialization.PowerBIPartSerializerExtensions.DeserializeSafe[T](IPowerBIPartSerializer`1 serializer, Boolean isOptional) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\IPowerBIPartSerializer.cs:line 41
An unhandled exception occurred.
PbiTools.Serialization.PbixProjSerializationException: The PBIX part at 'C:\PowerBIDevelopment\download\Reports\Sales\Sales - Local\Extract\Report' could not be deserialized and is marked as not optional.
   at PbiTools.Serialization.PowerBIPartSerializerExtensions.DeserializeSafe[T](IPowerBIPartSerializer`1 serializer, Boolean isOptional) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\IPowerBIPartSerializer.cs:line 52
   at PbiTools.Model.PbixModel.FromFolder(String path) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Model\PbixModel.cs:line 205
   at PbiTools.Cli.CmdLineActions.CompilePbix(String folder, String outPath, PbiFileFormat format, Boolean overwrite) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Cli\Compile.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Program.cs:line 110
```

Thought the current version of pbi-tools might fix it, so upgraded from pbi-tools.1.0.0-rc.2+preview.4 to pbi-tools.1.0.0-rc.4, but no luck...

**pbi-tools info:** 
```
{
  "version": "1.0.0-rc.4",
  "edition": "Desktop",
  "build": "1.0.23129.1016",
  "pbixProjVersion": "0.13",
  "pbiBuildVersion": "2.116.966.0",
  "longPathsEnabled": false,
  "amoVersion": "19.64.0.0",
  "toolPath": "C:\\Program Files\\pbi-tools-desktop\\pbi-tools.exe",
  "locale": {
    "system": "en-US (1033)",
    "ui": "en-US (1033)"
  },
  "settings": {
    "PBITOOLS_LogLevel": null,
    "PBITOOLS_PbiInstallDir": null,
    "PBITOOLS_AppDataDir": null,
    "PBITOOLS_Debug": null,
    "PBITOOLS_UICulture": null,
    "PBITOOLS_EffectiveDate": null,
    "PBITOOLS_DefaultModelSerialization": null,
    "PBITOOLS_ExternalAmoPath": null
  },
  "runtime": {
    "platform": "Microsoft Windows 10.0.17763 ",
    "architecture": "X64",
    "framework": ".NET Framework 4.8.4614.0"
  },
  "pbiInstalls": [
    {
      "ProductVersion": "2.120.731.0 (23.08)",
      "Is64Bit": true,
      "InstallDir": "C:\\Program Files\\Microsoft Power BI Desktop\\bin",
      "SettingsDir": "C:\\Users\\maria.fleissner\\AppData\\Local\\Microsoft\\Power BI Desktop",
      "Location": "Installer"
    }
  ],
  "effectivePbiInstallDir": "C:\\Program Files\\Microsoft Power BI Desktop\\bin",
  "pbiSessions": [
    {
      "ProductName": "Microsoft Power BI Desktop",
      "ProductVersion": "2.120.731.0 (23.08)",
      "ExePath": "C:\\Program Files\\Microsoft Power BI Desktop\\bin\\PBIDesktop.exe",
      "ProcessId": 110900,
      "Port": 58440,
      "WorkspaceName": "AnalysisServicesWorkspace_5621faef-cb00-4722-bf08-4e2fd8c5b91a",
      "WorkspaceDir": "C:\\Users\\maria.fleissner\\AppData\\Local\\Microsoft\\Power BI Desktop\\AnalysisServicesWorkspaces\\AnalysisServicesWorkspace_5621faef-cb00-4722-bf08-4e2fd8c5b91a\\Data",
      "PbixPath": "C:\\PowerBIDevelopment\\download\\Reports\\Sales\\Sales - Local\\Sales - Local.pbix"
    }
  ]
}
```
Also tried the compile command using the pbi-tools.core cli - but no luck either. 

This is currently breaking our deployment workflow and we're not able to take any changes into production. So any advice/fix would be appreciated! 
Although some reports are still working - could it have anything to do with the report size? The one that's throwing the error has 90+ pages and is ~8.5 Mb in size...

**Comment by mfleifbrg** [comment]
Solved! 

Turns out that initially the extract to project folder already failed to complete correctly and therefore the compile process was probably missing some files (therefore NullReferenceException). 
Root cause was the standard windows file path length limit of 260 characters. Obviously, the file paths in the extract project folder get quite lengthy and exceeded that limit. Setting the registry entry for LongPathsEnabled to true fixed the issue.

**Comment by qwertylogandi** [comment]
Please be more specific on the the registry entry (path for example).

**Comment by mthierba** [comment]
> Please be more specific on the the registry entry (path for example).

If the root cause here is the Windows long paths issue, further details on that can be found on #56 and related commits.

For the registry entry, the repo already contains this `.reg` file which can simply be executed to create the setting:

https://github.com/pbi-tools/pbi-tools/blob/aedb33b225cd7ec797aaabfa8b00119f6cdaee0e/scripts/EnableWindowsLongPaths.reg#L1-L4
