### ISSUE TITLE
unhandled exception during generate-bim

### ISSUE THREAD

**Issue by mfleifbrg** [pbi-tools/pbi-tools#308]
Hi there,
 
during our workflow we are extracting pbix (datasaet) files to a project folder, to then generate pbit and bim files for git versioning.
During the bim file generation we are suddenly experiencing an unhandled exception: 

```
Reading PBIXPROJ settings from: C:\PowerBIDevelopment\download\Datasets\Sales\Sales_Dataset_TestMF\Extract\.pbixproj.json
Using Power BI Desktop install: 2.120.731.0 (23.08) at C:\Program Files\Microsoft Power BI Desktop\bin
An unhandled exception occurred.
Microsoft.AnalysisServices.Tabular.TomInternalException: An internal error has occured.
   at Microsoft.AnalysisServices.Tabular.Column.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.CalculatedTableColumn.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Table.<>c__DisplayClass149_0.<SerializeToJsonObject>b__6(Column obj)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AnalysisServices.Tabular.Table.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Model.<>c__DisplayClass245_0.<SerializeToJsonObject>b__6(Table obj)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AnalysisServices.Tabular.Model.SerializeToJsonObject(JsonObject result, SerializeOptions options, CompatibilityMode mode, Int32 dbCompatibilityLevel)
   at Microsoft.AnalysisServices.Tabular.Database.SerializeToJsonObject(JsonObject result, SerializeOptions options)
   at Microsoft.AnalysisServices.Tabular.Database.SerializeToNewJsonObject(SerializeOptions options)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeDatabase(Database database, SerializeOptions options)
   at PbiTools.Serialization.TabularModelSerializer.DeserializeTmdl() in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 532
   at PbiTools.Serialization.TabularModelSerializer.TryDeserialize(JObject& database) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 458
   at PbiTools.Cli.CmdLineActions.GenerateBim(String folder, Boolean generateDataSources, ExportTransforms transforms) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Cli\GenerateBim.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Program.cs:line 110
```

No clue where this is coming from. 
Any help on this is highly appreciated. 

Maria 

pbi-tool info: 

```
{
  "version": "1.0.0-rc.4",
  "edition": "Desktop",
  "build": "1.0.23129.1016",
  "pbixProjVersion": "0.13",
  "pbiBuildVersion": "2.116.966.0",
  "longPathsEnabled": true,
  "amoVersion": "19.64.0.0",
  "toolPath": "C:\\Program Files\\pbi-tools-desktop\\pbi-tools.exe",
  "locale": {
    "system": "en-US (1033)",
    "ui": "en-US (1033)"
  },
  "settings": {
    "PBITOOLS_LogLevel": null,
    "PBITOOLS_PbiInstallDir": null,
    "PBITOOLS_AppDataDir": null,
    "PBITOOLS_Debug": null,
    "PBITOOLS_UICulture": null,
    "PBITOOLS_EffectiveDate": null,
    "PBITOOLS_DefaultModelSerialization": null,
    "PBITOOLS_ExternalAmoPath": null
  },
  "runtime": {
    "platform": "Microsoft Windows 10.0.17763 ",
    "architecture": "X64",
    "framework": ".NET Framework 4.8.4614.0"
  },
  "pbiInstalls": [
    {
      "ProductVersion": "2.120.731.0 (23.08)",
      "Is64Bit": true,
      "InstallDir": "C:\\Program Files\\Microsoft Power BI Desktop\\bin",
      "SettingsDir": "C:\\Users\\maria.fleissner\\AppData\\Local\\Microsoft\\Power BI Desktop",
      "Location": "Installer"
    }
  ],
  "effectivePbiInstallDir": "C:\\Program Files\\Microsoft Power BI Desktop\\bin",
  "pbiSessions": []
```

**Comment by mfleifbrg** [comment]
@mthierba 
Any idea on this? 
If more information is required, I'd be happy to investigate the issue in a joint teams session as well. 

Cheers, Maria

**Comment by mfleifbrg** [comment]
@mthierba 
Any idea on this? 
If more information is required I would be happy to investigate the issue in a joint teams session as well. 

Cheers, Maria

**Comment by mthierba** [comment]
Hi Maria,
looking at the error log, this is an error coming from Microsoft's TOM library whilst serializing a column for a calculated table. You appear to be using TMDL source in your project. Did you try loading the same TMDL folder via Tabular Editor, and are you experiencing the same problem there? I won't be able to diagnose this any further without access to your project files, unfortunately. I appreciate sharing those might not be an option for you, though.
Mathias
