### ISSUE TITLE
Model Serialisation Error pbi-tools 1.0.0-rc.7 & TE 2.21.0

### ISSUE THREAD

**Issue by quinse** [pbi-tools/pbi-tools#316]
Hi, thanks again for an awesome tool. I currently have TE v2.21.0 and I also have your latest pbi-tools release 1.0.0-rc.7 that should align. However when I convert from a Legacy PBIXproj folder structure to Raw serialization, make a change in TE and then try to convert it back to Legacy serialization I am recieving the following error:

PS C:\Users\I98519\Bitbucket\cars\pbi_datasets> **pbi-tools convert .\cars_corporate_dataset -modelSerialization Legacy -overwrite**
Reading PBIXPROJ settings from: C:\Users\I98519\Bitbucket\cars\pbi_datasets\cars_corporate_dataset\.pbixproj.json
Using Power BI Desktop install: 2.122.1066.0 (23.10) at C:\Program Files\Microsoft Power BI Desktop\bin
Extracting PBIX file to: C:\Users\I98519\Bitbucket\cars\pbi_datasets\cars_corporate_dataset
Version [1.25] extracted to: C:\Users\I98519\Bitbucket\cars\pbi_datasets\cars_corporate_dataset\Version.txt
Connections extracted to: C:\Users\I98519\Bitbucket\cars\pbi_datasets\cars_corporate_dataset\Connections.json
Metadata extracted to: C:\Users\I98519\Bitbucket\cars\pbi_datasets\cars_corporate_dataset\ReportMetadata.json
Settings extracted to: C:\Users\I98519\Bitbucket\cars\pbi_datasets\cars_corporate_dataset\ReportSettings.json
DiagramLayout extracted to: C:\Users\I98519\Bitbucket\cars\pbi_datasets\cars_corporate_dataset\DiagramLayout.json
Using tabular model serialization mode: Legacy
An unhandled exception occurred.
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable`1 value)
   at PbiTools.Serialization.TabularModelSerializer.ConvertExpression(JToken j)
   at PbiTools.Serialization.TabularModelSerializer.SerializeTablePartitions(JObject table, IProjectFolder modelFolder, String pathPrefix, IQueriesLookup idCache)
   at PbiTools.Serialization.TabularModelSerializer.SerializeTables(JObject db, IProjectFolder modelFolder, IQueriesLookup idCache, ModelMeasureSettings measureSettings)
   at PbiTools.Serialization.TabularModelSerializer.SerializeLegacy(JObject db)
   at PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings)
   at PbiTools.Model.PbixModelConverter.SaveAs(String outputPath)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args)

**Comment by quinse** [comment]
Sure, thanks, what is your email address?

**Comment by mthierba** [comment]
It's on the org profile: GitHub.com/pbi-tools

________________________________

**Comment by quinse** [comment]
Great thanks, email sent.

**Comment by quinse** [comment]
Oh sorry the first time we ran into the error we had an expression, I just
didn't add one this time before I sent the file. Let me test again with an
expression and I'll get back to you.

**Comment by quinse** [comment]
Apologies for wasting your time, this was the problem all along. Thanks for checking/
