### ISSUE TITLE
Deploy new Power BI tmdl model 

### ISSUE THREAD

**Issue by rednax1994** [pbi-tools/pbi-tools#326]
I've converted my Power BI model to the new tmdl using Power BI Desktop. When trying to deploy this using pbi-tools I'm getting a compatibilityViolationException. In my model i'm using the field parameters and on this one the deploy seems to be breaking. 
Below is the error message:
Microsoft.AnalysisServices.Tabular.CompatibilityViolationException: The usage of [model 'Model'].[table '.Self-Service Dimensions (IB - Data)'].[related column details] is not supported at AnalysisServices mode.
   at Microsoft.AnalysisServices.Tabular.Database.SerializeToJsonObject(JsonObject result, SerializeOptions options)
   at Microsoft.AnalysisServices.Tabular.Database.SerializeToNewJsonObject(SerializeOptions options)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.SerializeDatabase(Database database, SerializeOptions options)
   at PbiTools.Serialization.TabularModelSerializer.DeserializeTmdl() in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 565
   at PbiTools.Serialization.TabularModelSerializer.TryDeserialize(JObject& database) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 493
   at PbiTools.Serialization.PowerBIPartSerializerExtensions.DeserializeSafe[T](IPowerBIPartSerializer`1 serializer, Boolean isOptional) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Serialization\IPowerBIPartSerializer.cs:line 41
   
I'm not sure what i need to do to make sure that this is not a problem anymore.

**Comment by mthierba** [comment]
Sounds like the database.compatibilityLevel isn't set (or not to the right level). Could you check?

**Comment by rednax1994** [comment]
Hi Mathias, 
The compatibilityLevel is set for 1567 as set by Power BI desktop itself.

**Comment by mthierba** [comment]
If the issue is related to field params, it's likely that the problem is related to CompatibilityMode (not Level). Are you using an outdated version of pbi-tools? The latest versions should be setting the mode correctly. I distinctly remember fixing that.

**Comment by rednax1994** [comment]
The compatibilityMode gets removed on save by Power BI. Therefor I would need to write a script to include it on every pipeline run. That is ok. but if you say it should be inherently set by pbi-tools then maybe something else goes wrong. I'm using ghcr.io/pbi-tools/pbi-tools-core:latest

**Comment by mthierba** [comment]
That's useful to know. It *should* work without any further external intervention. Will raise it with the team internally. You have a workaround for now, though.

**Comment by rednax1994** [comment]
It's interesting, when you add the compatibilityMode: powerBI I still get an error which i'm not understanding at this point:
System.AggregateException: One or more errors occurred. (Cannot convert value '' to required type 'String'. Check path 'name', line 2, position 14.)
 ---> Microsoft.AnalysisServices.JsonSerializationException: Cannot convert value '' to required type 'String'. Check path 'name', line 2, position 14.
   at Microsoft.AnalysisServices.Tabular.Json.JsonPropertyHelper.ConvertJsonValueToString(JToken rawJsonValue)
   at Microsoft.AnalysisServices.Tabular.Database.ReadPropertyFromJson(JProperty jsonProp, DeserializeOptions options, CompatibilityMode mode)
   at Microsoft.AnalysisServices.Tabular.Database.DeserializeFromJsonObject(JObject jsonObj, DeserializeOptions options, CompatibilityMode mode)
   at Microsoft.AnalysisServices.Tabular.JsonSerializer.DeserializeDatabase(String json, DeserializeOptions options, CompatibilityMode mode)
   at PbiTools.Deployments.DeploymentManager.DeployDatasetAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 128
   at PbiTools.Deployments.DeploymentManager.DeployAsync(String profileName, String environment) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.cs:line 91
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Cli\Deploy.cs:line 41
--- End of stack trace from previous location ---

**Comment by mthierba** [comment]
Assign a name to both, the Database and the Model, object. That should fix this problem and is a known issue.

**Comment by rednax1994** [comment]
Awesome, thank you very much for the explanation.
