### ISSUE TITLE
PbiTools.PbiToolsCliException: Compiling a project containing a data model into a PBIX file is not supported.

### ISSUE THREAD

**Issue by tapasnavex** [pbi-tools/pbi-tools#333]
We are using DirectQuery mode for our project. I have extracted pbix file in Git repo, while initiating deploy from pbi-tools, I am getting below error.

Any suggestion, what am I missing ?

`An unhandled exception occurred.
System.AggregateException: One or more errors occurred. ---> PbiTools.PbiToolsCliException: Compiling a project containing a data model into a PBIX file is not supported. Please compile into a PBIT file instead.
   at PbiTools.Model.PbixModel.ToFile(String path, PbiFileFormat format, JObject connectionsOverwrite, IDependenciesResolver dependenciesResolver) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Model\PbixModel.cs:line 335
   at PbiTools.Deployments.DeploymentManager.CompileReportForDeployment(PbiDeploymentOptions options, String displayName, String pbixProjFolder, String tempDir, IDictionary`2 parameters, JObject connectionsOverwrite) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 286
   at PbiTools.Deployments.DeploymentManager.<>c__DisplayClass42_0.<GenerateReportsFromFolderSource>b__0(DeploymentSourceInfo folder) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 232
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PbiTools.Deployments.DeploymentManager.<DeployReportAsync>d__38.MoveNext() in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.cs:line 88
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Cli\Deploy.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Program.cs:line 110
---> (Inner Exception #0) PbiTools.PbiToolsCliException: Compiling a project containing a data model into a PBIX file is not supported. Please compile into a PBIT file instead.
   at PbiTools.Model.PbixModel.ToFile(String path, PbiFileFormat format, JObject connectionsOverwrite, IDependenciesResolver dependenciesResolver) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Model\PbixModel.cs:line 335
   at PbiTools.Deployments.DeploymentManager.CompileReportForDeployment(PbiDeploymentOptions options, String displayName, String pbixProjFolder, String tempDir, IDictionary`2 parameters, JObject connectionsOverwrite) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 286
   at PbiTools.Deployments.DeploymentManager.<>c__DisplayClass42_0.<GenerateReportsFromFolderSource>b__0(DeploymentSourceInfo folder) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 232
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PbiTools.Deployments.DeploymentManager.<DeployReportAsync>d__38.MoveNext() in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Report.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.cs:line 88<---`

**Comment by mthierba** [comment]
The Compile command can only be used with a PBIX target for "thin" reports, i.e. ones without an embedded model. Only a PBIT target is supported otherwise.

**Comment by tapasnavex** [comment]
Thanks for the quick response. I did a Dataset mode and it works fine when I give specific folder name in path, but I have multiple reports (sub-folders), tried wild card but its not accepting.

  "deployments": {
    "Reports": {
      "mode": "Dataset",
      "source": {
        "type": "Folder",
        "**path": "./"**
      }
      

Root
- Reports
- - Report1Folder
- - Report2Folder


`pbi-tools deploy ./Reports Reports  DEV -whatIf`

`Reading PBIXPROJ settings from: C:\Dev\dtdtdtt\Reports\.pbixproj.json
=== Deployment WhatIf mode enabled ===
Starting deployment 'Reports' into environment: DEV ...
Determining dataset from Folder source: "./"`

**Comment by mthierba** [comment]
For `Dataset` deployment mode, wildcards are not supported. pbi-tools is designed for enterprise scenarios and assumes that semantic models are managed and deployed individually. If you want to manage multiple semantic models within the same repository, please create individual deployment profiles for each.

**Comment by tapasnavex** [comment]
Got it. Need your suggestion on our case. I have pbix files (DirectQuery). Below are the steps I followed.
1. Extracted pbix using  `pbi-tools extract './Reports/abc.pbix'`
2. While trying to deploy those extracted contents to workspace, I am getting error "**PbiTools.PbiToolsCliException: Compiling a project containing a data model into a PBIX file is not supported. Please compile into a PBIT file instead.**"

My doubt is, I am nowhere doing compilation, I guess its happening in below command of yaml file.
`run: /app/pbi-tools/pbi-tools.core deploy ./Reports "$PROFILE" "$ENVIRONMENT"`

So, where can I define the file type here for deployment?

**Comment by mthierba** [comment]
It looks like you want to deploy a dataset (semantic model) instead of a (thin) report. The `Report` deployment mode is only designed for thin reports (from extracted sources). Do create a `Dataset` deployment manifest similar to this example: https://github.com/pbi-tools/dataset-devops-demo/blob/main/.pbixproj.json

**Comment by tapasnavex** [comment]
I had tried the above approach, problem is I have multiple reports and path parameter in Dataset mode is hardcoded. If I give path for a specific folder it works, but how do I traverse across all folder ? One option could be creating number of profiles, but again if in future I add a new report, I have to change the pbixproj file as well.

Current approach I have followed is, directly publishing pbix, then deletes their dataset and rebind them to semantic model. In this, I can't compare or multi developer can't work as its a binary file.

I am looking for a approach, which will convert my pbix fles into thin report, then publish them.. latter I will rebind them to the semantic dataset.

**Comment by mthierba** [comment]
Yes, I would strongly agree to convert your PBIX projects into thin reports and separate model development from report development. Then you just need one `Dataset` profile for your model and one `Report` profile for all your reports.

**Comment by tapasnavex** [comment]
Would mind guiding me how can I, convert my current PBIX into thin project and separate model/Dataset?

What I tried so far -
I extracted the pbix to a folder, then deleted the Model folder. Updated the connecion file wih details of my symantec dataset. Now, I am able to publish the reports to workspace. But, when I compile the extracted project (files) although it gives the pbix file, but it fails to load on Power BI desktop with object reference error (I think something related to Model.

**Comment by tapasnavex** [comment]
Forget about above question, seems I figure that out and able to make it work for my requirement as of now.
Thanks @mthierba .

**Comment by mthierba** [comment]
For reference, the *Cannot convert value '' to required type 'String'. Check path 'name'* error can be addressed by adding a name to the database declaration in `database.tmdl`: https://github.com/pbi-tools/sales-sample/blob/2aae8e7f40b812429cd72520402b535be8e4b8f3/Sales.SemanticModel/definition/database.tmdl#L1

That was an issue in an earlier version on TOM.
