### ISSUE TITLE
Deployment logging bug with malformed markup

### ISSUE THREAD

**Issue by mthierba** [pbi-tools/pbi-tools#338]
> Model deployment succeeded.
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. (Encountered malformed markup tag at position 10.)
---> System.InvalidOperationException: Encountered malformed markup tag at position 10.
at Spectre.Console.MarkupTokenizer.ReadMarkup() in //src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs:line 192
at Spectre.Console.MarkupTokenizer.MoveNext() in //src/Spectre.Console/Internal/Text/Markup/MarkupTokenizer.cs:line 27
at Spectre.Console.MarkupParser.Parse(String text, Style style) in //src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 17
at Spectre.Console.Markup..ctor(String text, Style style) in //src/Spectre.Console/Widgets/Markup.cs:line 42
at Spectre.Console.TableExtensions.<>c.b__6_0(String column) in //src/Spectre.Console/Extensions/TableExtensions.cs:line 160
at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
at Spectre.Console.TableExtensions.AddRow(Table table, String[] columns) in //src/Spectre.Console/Extensions/TableExtensions.cs:line 160
at PbiTools.Deployments.DeploymentManager.ReportPartitionStatus(Model model, ConsoleOptions consoleOptions) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 469
at PbiTools.Deployments.DeploymentManager.DeployDatasetAsync(PbiDeploymentManifest manifest, String label, String environment) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 294
at PbiTools.Deployments.DeploymentManager.DeployAsync(String profileName, String environment) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Deployments\DeploymentManager.cs:line 91
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Cli\Deploy.cs:line 41
--- End of stack trace from previous location ---
at PowerArgs.ArgAction.Invoke()
at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\rc.8\src\PBI-Tools\Program.cs:line 104

See #336

**Comment by mthierba** [comment]
Fixed in 1.0.0 release
