### ISSUE TITLE
An unhandled exception occurred.

### ISSUE THREAD

**Issue by paras1201** [pbi-tools/pbi-tools#342]
Hi @mthierba 

I'm using a Power BI Desktop Report server (on-premise) Sept23 version. 
I'm unable to run the "extract" command as shown below.
Also note that I'm unable to run "pbi-tools info" command as well. 
Pls note that my colleague uses the same power bi desktop version however she is able to extract the pbix to folder.

***********ERROR1: EXTRACT*************

C:\Users\pat>pbi-tools extract "C:\Users\HELA\OneDrive - HEXA Corporation\Desktop\Backup_Desktop_new_laptop_08Jul22\Trash\New folder (89)\Material Cost Analysis_R6.pbix"
pbi-tools | Copyright (C) Mathias Thierbach 2018-2024

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See <https://goto.pbi.tools/license> for full license details.

An unhandled exception occurred.
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.PowerBI.Packaging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. General Exception (Exception from HRESULT: 0x80131500)
File name: 'Microsoft.PowerBI.Packaging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Exception: No 64-bit Power BI Desktop installation found
   at PbiTools.Utils.DependenciesResolver.GetPBIInstall() in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Utils\DependenciesResolver.cs:line 87
   at PbiTools.Utils.DependenciesResolver.GetEffectivePowerBiInstallDir() in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Utils\DependenciesResolver.cs:line 195
   at PbiTools.Utils.DependenciesResolver.<>c__DisplayClass13_0.<AssemblyResolve>b__0(Object sender, ResolveEventArgs args) in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Utils\DependenciesResolver.cs:line 102
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at PbiTools.PowerBI.PbixReader..ctor(String pbixPath, IDependenciesResolver resolver)
   at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Nullable`1 pid, Nullable`1 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization, Boolean watch) in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Cli\Extract.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Program.cs:line 124

***********ERROR2: PBIINFO*************
pbi-tools | Copyright (C) Mathias Thierbach 2018-2024

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See <https://goto.pbi.tools/license> for full license details.

An unhandled exception occurred.
System.Exception: No 64-bit Power BI Desktop installation found
   at PbiTools.Utils.DependenciesResolver.GetPBIInstall() in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Utils\DependenciesResolver.cs:line 87
   at PbiTools.Utils.DependenciesResolver.GetEffectivePowerBiInstallDir() in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Utils\DependenciesResolver.cs:line 195
   at PbiTools.Cli.CmdLineActions.Info(Boolean checkDownloadVersion) in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Cli\Info.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\rc.9\src\PBI-Tools\Program.cs:line 124

**Comment by mthierba** [comment]
Ensure the latest version of Power BI Desktop is installed: https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop

The error message indicates that it could not be located on your machine.

**Comment by paras1201** [comment]
I tested it on latest version i.e. May24 as well however it's causing the same error.
I do have Power BI Desktop Report Server (64-bit) installed.
Is it something to do with the directory where Power BI is installed or exe file is located?

**Comment by paras1201** [comment]
@mthierba .. 
Fyi
It works fine with the Power BI Desktop for service/cloud version but not with the on-premise version.
Really appreciate the effort of building this. It's a life saver!!

**Comment by mthierba** [comment]
Thanks for checking - pbi-tools was never designed to work with the on-prem version - if it did work in that context, it would be accidental. 
If there were sufficient demand, explicit on-prem support could be made available under a separate, commercial, license.
