### ISSUE TITLE
Unhandled exception at extract

### ISSUE THREAD

**Issue by peterbud** [pbi-tools/pbi-tools#49]
I have tried to run the beta 6 on a small local PBIX. 

```
C:\Program Files\pbi-tools\pbi-tools.exe' extract '.\dataModel.pbix' -extractFolder './data'
```
I got the following error:

```
Using Power BI Desktop install: 2.98.882.0 (21.10) at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.98.882.0_x64__8wekyb3d8bbwe\bin
An unhandled exception occurred.
System.IO.FileFormatException: File contains corrupted data.
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
   at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at Microsoft.PowerBI.Packaging.PowerBIPackager.Open(Stream storageStream, Boolean& requiresConversionToReportLayout, Byte[]& securityBindings, Version& pbixFileVersion, Boolean skipValidation)
   at PbiTools.PowerBI.PbixReader..ctor(String pbixPath, IDependenciesResolver resolver) in E:\pbi-tools\pbi-tools-cli\src\PBI-Tools\PowerBI\PbixReader.cs:line 42
   at PbiTools.CmdLineActions.Extract(String pbixPath, Int32 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization) in E:\pbi-tools\pbi-tools-cli\src\PBI-Tools\CmdLineActions.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in E:\pbi-tools\pbi-tools-cli\src\PBI-Tools\Program.cs:line 76
```

**Comment by pfayika1** [comment]
hello @mthierba, I also ran into the same error message. It looks like it occurs when I am logged into Powerbi desktop using my corporate account, I think there could be some sensitivity labels applied. When logging out of my corporate account the error message disappeared.

thank you
