### ISSUE TITLE
Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.

### ISSUE THREAD

**Issue by didierterrien** [pbi-tools/pbi-tools#87]
Hi Mathias,

Thank you for the fantastic tool!

I succeeded to extract Adventure works but then I tried with Contoso which is 55 Mb and I got the issue down below. I'm not sure it is linked to file size. 

I put pbi-tools files in the same folder than the pbix  
![image](https://user-images.githubusercontent.com/37301981/154472567-7eb051e9-6f5c-4598-8394-6446db1db84d.png)

And I used this command line :   pbi-tools extract "Contoso.pbix"  from the same folder

It seems I cannot upload the pbix here even if I rename it as a zip so I try to send it to you by another way.

C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools>pbi-tools extract "C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools\Contoso.pbix"
Using Power BI Desktop install: 2.100.684.0 (21.12) at C:\Program Files\Microsoft Power BI Desktop\bin
MSMDSRV.EXE found at C:\Program Files\Microsoft Power BI Desktop\bin\msmdsrv.exe
Working directory: C:\Users\MyUserName\AppData\Local\Temp\tmp7CBC.tmp
Tabular Server process launched successfully. Port: 51001
Model image from PBIX loaded successfully.
Extracting PBIX file to: C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools\Contoso
Version [1.22] extracted to: C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools\Contoso\Version.txt
Report extracted to: C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools\Contoso\Report
Metadata extracted to: C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools\Contoso\ReportMetadata.json
Settings extracted to: C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools\Contoso\ReportSettings.json
DiagramLayout extracted to: C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools\Contoso\DiagramLayout.json
DiagramViewState extracted to: C:\Users\MyUserName\Documents\Power BI Sidetools\pbi-tools\Contoso\DiagramViewState.json
Using tabular model serialization mode: Default
An unhandled exception occurred.
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   à Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   à PbiTools.Serialization.TabularModelSerializer.<>c__DisplayClass33_0.<WriteMeasureXml>b__0(TextWriter writer) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:ligne 726
   à PbiTools.FileSystem.ProjectFolder.WriteFile[T](String path, Func`2 factory, Action`1 callback) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\FileSystem\ProjectFolder.cs:ligne 151
   à PbiTools.FileSystem.ProjectFolder.WriteText(String path, Action`1 onTextWriterAvailable) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\FileSystem\ProjectFolder.cs:ligne 135
   à PbiTools.Serialization.TabularModelSerializer.SerializeMeasures(JObject table, IProjectFolder modelFolder, String pathPrefix) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:ligne 173
   à PbiTools.Serialization.TabularModelSerializer.SerializeTables(JObject db, IProjectFolder modelFolder, IQueriesLookup idCache) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:ligne 123
   à PbiTools.Serialization.TabularModelSerializer.Serialize(JObject db) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:ligne 93
   à PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Model\PbixModel.cs:ligne 293
   à PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Int32 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Cli\Extract.cs:ligne 71
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à PowerArgs.ArgAction.Invoke()
   à PbiTools.Program.Main(String[] args) dans X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Program.cs:ligne 82

**Comment by mthierba** [comment]
Issue confirmed. I can reproduce it with the file you shared privately.

**Comment by mthierba** [comment]
I'll put a few general notes around debugging/troubleshooting here for reference, and for others, too.

`pbi-tools` allows you to easily change the verbosity of logs emitted. _LogLevel_ is controlled via the `PBITOOLS_LogLevel` environment variable. Use `pbi-tools info` to get a list of all environment variables supported an their exact names:

```
{
  "version": "1.0.0-beta.9+220216",
  "edition": "Desktop",
...
  "settings": {
    "PBITOOLS_LogLevel": null,
    "PBITOOLS_PbiInstallDir": null,
    "PBITOOLS_AppDataDir": null,
    "PBITOOLS_Debug": null
  },
  "runtime": {
...}
```

Switch logging to the "Debug" level like so:

    $env:PBITOOLS_LogLevel = "Debug"

If you then re-run `pbi-tools extract` it'll produce a lot more output:

```
...
No existing or invalid PBIXPROJ file found at X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\.pbixproj.json. Generating new project file.
Extracting PBIX file to: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso
Version [1.22] extracted to: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\Version.txt
Report extracted to: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\Report
Metadata extracted to: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\ReportMetadata.json
Settings extracted to: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\ReportSettings.json
DiagramLayout extracted to: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\DiagramLayout.json
DiagramViewState extracted to: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\DiagramViewState.json
Using tabular model serialization mode: Default
An unhandled exception occurred.
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at PbiTools.Serialization.TabularModelSerializer.<>c__DisplayClass33_0.<WriteMeasureXml>b__0(TextWriter writer) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 726
   at PbiTools.FileSystem.ProjectFolder.WriteFile[T](String path, Func`2 factory, Action`1 callback) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 151
   at PbiTools.FileSystem.ProjectFolder.WriteText(String path, Action`1 onTextWriterAvailable) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 135
   at PbiTools.Serialization.TabularModelSerializer.SerializeMeasures(JObject table, IProjectFolder modelFolder, String pathPrefix) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 173
   at PbiTools.Serialization.TabularModelSerializer.SerializeTables(JObject db, IProjectFolder modelFolder, IQueriesLookup idCache) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 123
   at PbiTools.Serialization.TabularModelSerializer.Serialize(JObject db) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 93
   at PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Model\PbixModel.cs:line 293
   at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Int32 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Cli\Extract.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Program.cs:line 82
```

You can see that the error occurs as the tabular model is being serialized, however, we're still missing further details. Lets go one step further and set the log level to "Verbose": 

    $env:PBITOOLS_LogLevel = "Verbose"

Now, when re-running `pbi-tools extract`, all hell breaks lose, and you get an abundance of log messages, including those right before the error occurs:

```
Writing file: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\Model\tables\Sales\measures\Sales lines.xml
File written: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\Model\tables\Sales\measures\Sales lines.xml
Writing file: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\Model\tables\Sales\measures\Sales lines.dax
File written: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\Model\tables\Sales\measures\Sales lines.dax
Writing file: X:\pbi-tools\ISSUES\87 Contoso-JsonParse\Contoso\Model\tables\Sales\measures\Sales amount.xml
An unhandled exception occurred.
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at PbiTools.Serialization.TabularModelSerializer.<>c__DisplayClass33_0.<WriteMeasureXml>b__0(TextWriter writer) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 726
   at PbiTools.FileSystem.ProjectFolder.WriteFile[T](String path, Func`2 factory, Action`1 callback) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 151
   at PbiTools.FileSystem.ProjectFolder.WriteText(String path, Action`1 onTextWriterAvailable) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\FileSystem\ProjectFolder.cs:line 135
   at PbiTools.Serialization.TabularModelSerializer.SerializeMeasures(JObject table, IProjectFolder modelFolder, String pathPrefix) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 173
   at PbiTools.Serialization.TabularModelSerializer.SerializeTables(JObject db, IProjectFolder modelFolder, IQueriesLookup idCache) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 123
   at PbiTools.Serialization.TabularModelSerializer.Serialize(JObject db) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 93
   at PbiTools.Model.PbixModel.ToFolder(String path, PbixProjectSettings settings) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Model\PbixModel.cs:line 293
   at PbiTools.Cli.CmdLineActions.Extract(String pbixPath, Int32 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Cli\Extract.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\issue-85\src\PBI-Tools\Program.cs:line 82
```

We now know that a json serialization error happens when the `'Sales'[Sales amount]` measure is being serialized into a XML file. This is a `pbi-tools` specific serialization format enabling better readability of the the various XML-encoded custom attributes PBI Desktop generates. It also means this issue has nothing to do with the underlying TMSL.

We can still go further, though! `pbi-tools extract` supports customizing the tabular model serialization mode. We can set it to `Raw` to avoid any further transforms and simply output the TMSL is is comes from AS. That will allow us to eliminate this error and look into the details of that measure:

    pbi-tools extract .\Contoso.pbix -modelSerialization Raw

Everything is extracted fine now, and we get a single "database.json" inside the "Model" folder:

<img width="154" alt="image" src="https://user-images.githubusercontent.com/3763662/154707552-4535eaf4-dc16-4a34-a757-6550c9bbaeed.png">

That exposes the original Json format for the measure:

```
          {
            "name": "Sales amount",
            "description": "This is the sales amount description",
            "expression": [
              "",
              "VAR Var1 = SUMX ( Sales, 'Sales'[UnitPrice] * Sales[Salesquantity] )",
              "VAR Var2 = SUMX ( Sales, 'Sales'[UnitPrice] * Sales[Salesquantity] - Sales[DiscountAmount] )",
              "VAR Var3 = FILTER ( 'Product', 'Product'[ClassName] = \"Deluxe\" )",
              "//VAR DBG_MAIN_CONTEXT = FILTER( 'Product', 'Product'[Classname] = \"Deluxe\" )",
              "//VAR DBG_MAIN_SORT_ORDER = 'Product'[Unitcost] DESC",
              "//VAR DBG_ROWS_LIMIT = 10 ",
              "VAR DBG_TABLE_YourTable = ADDCOLUMNS( VALUES('Product'[ClassName]), \"YourMeasureName\", [Sales lines] )  ",
              "RETURN Var2 "
            ],
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "displayFolder": "_Measures&columns",
            "lineageTag": "a3b98e4b-70f7-4c7c-8975-14089125f3ac",
            "kpi": {
              "targetExpression": "2000",
              "statusGraphic": "Three Stars Colored",
              "statusExpression": "1",
              "trendGraphic": "Traffic Light - Single",
              "trendExpression": "1"
            },
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"CurrencyCustom\" Accuracy=\"0\" ThousandSeparator=\"True\"><Currency LCID=\"1036\" DisplayName=\"€ French (France)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
```

It's the `kpi` element, which throws at this line: https://github.com/pbi-tools/pbi-tools/blob/1.0.0-beta.8/src/PBI-Tools/Serialization/TabularModelSerializer.cs#L729

I had made the assumption that all json properties not already handles specially would be string values. In this case `kpi` is a json object and fails.

I'll fix this by checking the property value type first. In the meantime, use the `Raw` serialization mode.

Mid-term, #36 will address this issue differently - I'd like to standardize the model serialization format to be fully aligned with Tabular Editor, which extracts all tabular elements using their original json format. That'll allow much better workflows using both tools against the same project folder.
