### ISSUE TITLE
An unhandled exception occurred. ... Cannot cast Newtonsoft.Json.Linq.JArray to ...

### ISSUE THREAD

**Issue by scottstauffer-fc** [pbi-tools/pbi-tools#93]
I'm having issues **extract**ing this report with **pbi-tools.exe**
Anyone know what the issue might be?

```
C:\ReportPath>C:\ToolsPath\pbi-tools.exe extract "BadReport.pbix"
Using Power BI Desktop install: 2.102.683.0 (22.02) at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.102.683.0_x64__8wekyb3d8bbwe\bin
MSMDSRV.EXE found at C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.102.683.0_x64__8wekyb3d8bbwe\bin\msmdsrv.exe
Working directory: C:\Source\AppData\Local\Temp\tmpA61F.tmp
Shadow-copying msmdsrv...
Using msmdsrv from shadow-copied location: C:\Temp\PBITOOLS_AppDataDir\Microsoft.MicrosoftPowerBIDesktop_2.102.683.0_x64__8wekyb3d8bbwe\msmdsrv.exe
Tabular Server process launched successfully. Port: 64328
Model image from PBIX loaded successfully.
Extracting PBIX file to: C:\ReportPath\BadReport
Version [1.25] extracted to: C:\ReportPath\BadReport\Version.txt
Connections extracted to: C:\ReportPath\BadReport\Connections.json
Report extracted to: C:\ReportPath\BadReport\Report
Metadata extracted to: C:\ReportPath\BadReport\ReportMetadata.json
Settings extracted to: C:\ReportPath\BadReport\ReportSettings.json
DiagramLayout extracted to: C:\ReportPath\BadReport\DiagramLayout.json
Using tabular model serialization mode: Default
An unhandled exception occurred.
System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JArray to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at PbiTools.Serialization.TabularModelSerializer.<>c__DisplayClass30_0.<WriteMeasureXml>b__0(TextWriter writer)
   at PbiTools.FileSystem.ProjectFolder.WriteFile[T](String path, Func`2 factory, Action`1 callback)
   at PbiTools.FileSystem.ProjectFolder.WriteText(String path, Action`1 onTextWriterAvailable)
   at PbiTools.Serialization.TabularModelSerializer.SerializeMeasures(JObject table, IProjectFolder modelFolder, String pathPrefix)
   at PbiTools.Serialization.TabularModelSerializer.SerializeTables(JObject db, IProjectFolder modelFolder, IQueriesLookup idCache)
   at PbiTools.Serialization.TabularModelSerializer.Serialize(JObject db)
   at PbiTools.Model.PbixModel.ToFolder(String path)
   at PbiTools.CmdLineActions.Extract(String pbixPath, Int32 pbiPort, String extractFolder, ExtractActionCompatibilityMode mode, ModelSerializationMode modelSerialization, MashupSerializationMode mashupSerialization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args)

C:\ReportPath>
```

**Comment by mthierba** [comment]
Hi @scottstauffer-fc ,
This sounds exactly like #87. Mind having a look at my write-up there? It explains how to diagnose the issue and also provides a workaround. The fix is going to be straightforward.

**Comment by mthierba** [comment]
Confirmed as a bug. In your case the measure description is a multi-line string, serialized as a json array. `pbi-tools` assumes that _Description_ would always be a simple string.

This is probably a good moment (since #87 has the exact same root cause) to reconsider the (proprietary) xml format for measures and simply stick to json - keeping the payload as-is means there can't be any suprizes and the tool is able to handle formats it's never seen before.

I'll introduce a new _model_ serialization setting allowing users to decide between json and xml. Just have to figure out what should be the default moving forward (is json opt-in, or xml)? What do you think?

**Comment by scottstauffer-fc** [comment]
I'm glad you've had the time to look at this and found the root cause so quickly!

"Just have to figure out what should be the default moving forward (is json opt-in, or xml)? What do you think?"

I guess JSON should be the default if XML is unable to handle potential edge cases, that seem to be more likely going forward.
Adding a new format is likely no small change on your part.
